# -*- coding: utf-8 -*-
"""Entities (regex-detected in every chapter) and semantic edges (curated, each with a reason)."""
import re
I=re.I
# id, label, kind, regex, flags, gloss (short, from the thesis's own usage)
ENTITIES = [
 # --- methods / models
 ("tagm","TAGM (T-augmented Gaussian mixture)","method",r"\bTAGM\b",0,"Bayesian mixture: Gaussian per niche plus multivariate-t outlier component."),
 ("tagm-map","TAGM-MAP / EM","method",r"TAGM[- ]MAP|tagmMapTrain|expectation[- ]maximi[sz]ation|\bEM algorithm\b",I,"MAP inference for TAGM using the EM algorithm."),
 ("tagm-mcmc","TAGM-MCMC","method",r"TAGM[- ]MCMC|tagmMcmc",I,"Fully Bayesian TAGM using a collapsed Gibbs sampler."),
 ("mcmc","MCMC / Gibbs sampling","method",r"Markov[- ]chain Monte[- ]Carlo|\bMCMC\b|Gibbs sampler",I,"Sampling from posterior distributions."),
 ("svm","Support vector machine","method",r"support vector machine|\bSVMs?\b",0,"Kernel classifier used as the main baseline in ch. 2."),
 ("knn","k-nearest neighbours","method",r"[Kk][- ]nearest neighbou?rs?|\bKNN\b|\bK-NN\b",0,"Baseline classifier."),
 ("novelty-tagm","Novelty TAGM","method",r"Novelty TAGM",0,"TAGM extended with overfitted mixtures to find new niches."),
 ("overfitted","Overfitted mixtures","method",r"over-?fitted mixtures?",I,"More components than needed; unused ones stay empty."),
 ("psm","Posterior similarity matrix","method",r"posterior similarity matri(?:x|ces)",I,"N x N probability that two proteins share a component; invariant to label switching."),
 ("gp","Gaussian process regression","method",r"Gaussian process|Gaussian random field|\bGPs?\b|\bGRFs?\b",0,"Smooth non-parametric model of niche profiles along the gradient."),
 ("hmc","Hamiltonian Monte Carlo","method",r"Hamiltonian|\bHMC\b",0,"Used for GP hyperparameter updates."),
 ("toeplitz","Toeplitz / Trench-Durbin algorithms","method",r"Toeplitz|Trench|Durbin",0,"Fast inversion exploiting covariance structure."),
 ("bandle","BANDLE","method",r"\bBANDLE\b",0,"Bayesian analysis of differential localisation experiments."),
 ("mr","Movement-reproducibility (MR) method","method",r"movement[- ]reproducibility|\bMR (?:method|approach|plot|score)",I,"Itzhak et al.'s outlier-test approach to detect moving proteins."),
 ("polya","Pólya-Gamma augmentation","method",r"P[oó]lya[- ]Gamma",I,"Alternative correlated prior for allocations."),
 ("matdir","Matrix Dirichlet prior","method",r"matrix Dirichlet|\bMDir\b",I,"Joint prior over the pair of allocations."),
 ("pcprior","Penalised-complexity priors","method",r"penali[sz]ed[- ]complexity|\bPC priors?\b",I,"Weakly informative priors for GRF hyperparameters."),
 ("niw","Normal-inverse-Wishart prior","method",r"normal[- ]inverse[- ]Wishart|\bNIW\b",I,"Conjugate prior for Gaussian components."),
 ("entropy","Shannon entropy","method",r"Shannon entropy",I,"Uncertainty summary of localisation probabilities."),
 ("brier","Quadratic loss (Brier score)","method",r"quadratic loss|Brier score",I,"Scores probabilistic assignments."),
 ("f1","Macro-F1","method",r"[Mm]acro[- ]?F1|F1 score",0,"Classifier accuracy summary."),
 ("gelman","Gelman-Rubin diagnostic","method",r"Gelman[- ]Rubin|Gelman diagnostic",I,"MCMC convergence check."),
 ("phenodisco","phenoDisco","method",r"phenoDisco",0,"Existing novelty-detection algorithm."),
 ("labelswitch","Label switching","method",r"label[- ]switching",I,"Identifiability issue in mixtures."),
 ("priorpred","Prior predictive checks","method",r"prior predictive",I,"Used to calibrate priors."),
 ("eb","Empirical Bayes","method",r"empirical[- ]Bayes",I,"Optimise hyperparameters rather than sample them."),
 # --- experimental methods / assays
 ("hyperlopit","hyperLOPIT","assay",r"hyperLOPIT",0,"Density-gradient subcellular fractionation + TMT MS."),
 ("lopitdc","LOPIT-DC","assay",r"LOPIT-DC",0,"Differential-centrifugation variant."),
 ("dom","Dynamic Organellar Maps (DOM)","assay",r"Dynamic(?:al)? Organell?ar Maps|\bDOMs?\b",0,"Fast differential-centrifugation spatial proteomics."),
 ("tmt","TMT labelling","assay",r"\bTMT\b|[Tt]andem [Mm]ass [Tt]ag",0,"Isobaric multiplexing."),
 ("silac","SILAC","assay",r"\bSILAC\b",0,"Metabolic labelling."),
 ("crispr","CRISPR-Cas9","assay",r"CRISPR",0,"Knockout screens and gene tagging."),
 ("pca","PCA / t-SNE visualisation","assay",r"principal component|\bPCA\b|t-SNE",0,"Standard visualisation of profiles."),
 ("go","GO enrichment","assay",r"Gene Ontology|\bGO\b",0,"Over-representation tests on new phenotypes."),
 ("hpa","Human Protein Atlas","assay",r"Human Protein Atlas|\bHPA\b",0,"Microscopy-based validation resource."),
 # --- datasets / systems
 ("mesc","Mouse embryonic stem cells (E14TG2a)","dataset",r"mouse pluripotent|\bmESCs?\b|E14TG2a",0,"hyperLOPIT map of 5,032 proteins (Christoforou et al.)."),
 ("drosophila","Drosophila embryos","dataset",r"Drosophila",0,"LOPIT dataset, 888 proteins."),
 ("chicken","Chicken DT40","dataset",r"chicken|DT40",I,"LOPIT dataset."),
 ("u2os","U-2 OS cells","dataset",r"U-?2 ?OS",0,"hyperLOPIT and LOPIT-DC datasets."),
 ("hela","HeLa cells","dataset",r"HeLa",0,"Itzhak and Hirst DOM datasets."),
 ("hcmv","HCMV-infected fibroblasts","dataset",r"HCMV|cytomegalovirus|fibroblast",I,"Beltran et al. spatio-temporal maps."),
 ("toxo","Toxoplasma gondii","dataset",r"Toxoplasma|T\. gondii",0,"Apicomplexan parasite atlas."),
 ("yeast","Saccharomyces cerevisiae","dataset",r"cerevisiae|\byeast\b",I,"hyperLOPIT yeast dataset."),
 ("neuron","Mouse primary neurons","dataset",r"primary neurons?",I,"DOM dataset."),
 ("hek","HEK-293 cells","dataset",r"HEK-?293",0,"Used for the phenoDisco comparison."),
 ("egf","EGF stimulation (HeLa)","dataset",r"\bEGF\b",0,"Dynamic experiment with known re-localisations."),
 ("ap4","AP-4 knockout","dataset",r"\bAP-4\b",0,"Davies et al. DOM experiment."),
 ("ap5","AP-5 knockouts (Hirst)","dataset",r"\bAP-5\b|AP5Z1",0,"CRISPR knockouts coupled to DOM."),
 # --- software
 ("proloc","pRoloc / pRolocdata","software",r"pRoloc",0,"Bioconductor packages implementing the methods."),
 ("msnbase","MSnbase","software",r"MSnbase",0,"MS data structures."),
 ("bioc","Bioconductor","software",r"Bioconductor",0,"Open-source bioinformatics project."),
 # --- key terms
 ("markers","Marker proteins","term",r"marker proteins?|\bmarkers\b",I,"Proteins of a priori known single localisation."),
 ("outlier","Outlier component","term",r"outlier component|outlier proteins?",I,"Heavy-tailed component for proteins not in any niche."),
 ("multiloc","Multi-localisation","term",r"multi-?locali[sz]ation|multiple locations",I,"Proteins found in more than one compartment."),
 ("moonlight","Moonlighting proteins","term",r"moonlight",I,"Proteins carrying out more than one function."),
 ("diffloc","Differential localisation","term",r"differential(?:ly)? locali[sz]",I,"Assignment to different niches between conditions."),
 ("uq","Uncertainty quantification","term",r"uncertainty quantification|quantif(?:y|ying) (?:the )?uncertainty",I,"Central theme of the thesis."),
 ("semisup","Semi-supervised learning","term",r"semi-supervised",I,"Use of both labelled and unlabelled proteins."),
 ("noveltydet","Novelty detection","term",r"novelty detection",I,"Finding niches not in the annotation."),
 ("deduve","De Duve's fractionation principle","term",r"de Duve|De Duve",0,"Proteins co-fractionate with their organelle."),
]

# (source, target, type, basis, reason, pages, confidence)   ids may be chapters or sections
SEMANTIC = [
 ("ch3","ch2","implements_method","stated","Chapter 3 documents the software for the TAGM model introduced in chapter 2.",["57","59"],"high"),
 ("ch4","ch2","reuses_method","stated","Applies the Bayesian model from chapters 2-3 to Toxoplasma ('ideas developed in the previous two chapters').",["97","111"],"high"),
 ("ch4","ch3","reuses_method","stated","TAGM-MCMC run 'as described in the previous chapter' with minor modifications.",["111"],"high"),
 ("ch5","ch2","extends_model","stated","Novelty TAGM extends the TAGM mixture with extra components (overfitted mixture).",["131","132"],"high"),
 ("s4.5","ch5","answers_limitation","stated","Ch. 4 ends: TAGM cannot model unannotated niches; 'extended to allow additional niches to be discovered ... content of the next chapter'.",["121","122","123"],"high"),
 ("s2.6","ch5","answers_limitation","stated","Ch. 2 says methods to 'simultaneously assign proteins to organelles and detect un-annotated sub-cellular niches' are 'the content of a later chapter'.",["56"],"high"),
 ("s2.5","ch5","builds_on_result","inferred","The outlier-component analysis in ch. 2 (proteins fitting no known niche) is a precursor of ch. 5's search for unannotated niches; the author links the two on p. 56.",["45","56"],"medium"),
 ("s5.7","ch6","answers_limitation","stated","Ch. 5 notes a multivariate Gaussian ignores the ordering of fractions and suggests Gaussian processes; ch. 6 develops them.",["156","157"],"high"),
 ("ch6","ch2","compares_against","stated","TAGM (ch. 2) is the baseline model in the ch. 6 predictive comparison.",["181","182"],"high"),
 ("s6.4.3","s2.4","reuses_method","stated","Same 80/20 repeated cross-validation and quadratic-loss scoring as the ch. 2 benchmark.",["174","181","182"],"high"),
 ("ch6","ch5","same_concept","stated","Ch. 6 revisits the 'large protein complex' class as in ch. 5.",["183"],"medium"),
 ("ch7","ch6","reuses_method","stated","BANDLE's likelihood, GRF priors and sampler follow ch. 6 ('likelihood model is the same as the previous chapter').",["194","196","198"],"high"),
 ("ch7","ch2","reuses_method","stated","Outlier modelling 'as described in previous chapter' (heavy-tailed component, ch. 2).",["197"],"medium"),
 ("s5.3.2","s3.6.3","modifies_method","stated","Novelty TAGM cannot use the weakly informative prior on mixing proportions recommended in ch. 3.",["133"],"high"),
 ("s7.2","s6.5","answers_limitation","stated","Ch. 6 closes by asking which proteins change localisation upon stimulus; ch. 7 opens by turning to this 'dynamic question'.",["185","187"],"high"),
 ("s7.4.4","s2.4","same_dataset","stated","HCMV fibroblast maps (Beltran et al.) are among the 19 datasets used in ch. 2.",["33","218"],"high"),
 ("s7.4.4","s5.4.2","same_dataset","stated","HCMV and mock fibroblast maps at 24 hpi are analysed with Novelty TAGM in ch. 5 and with BANDLE in ch. 7.",["136","137","143","219"],"high"),
 ("s6.4.1","s2.4","same_dataset","stated","Drosophila and mESC datasets reused from ch. 2.",["174","180","182"],"high"),
 ("s7.4.2","s6.4.1","same_dataset","stated","Ch. 7 simulations start from the Drosophila dataset also used in ch. 6.",["174","203"],"high"),
 ("s5.4.1","s2.5","same_dataset","stated","mESC hyperLOPIT dataset reused in ch. 5.",["39","137"],"high"),
 ("s5.4.3","s2.4","same_dataset","stated","The HeLa (Itzhak and Hirst) datasets are in ch. 2's benchmark and are re-analysed in ch. 5.",["33","147"],"high"),
 ("s7.4.3","s2.4","same_dataset","inferred","The HeLa DOM data used for EGF stimulation (Itzhak et al.) are in the same family as the HeLa datasets in ch. 2's benchmark.",["33","210"],"medium"),
 ("s7.4.4","s7.4.3","same_concept","inferred","All three ch. 7 case studies apply the same BANDLE differential-localisation probability and rank-plot interpretation.",["200","210","219"],"medium"),
 ("ch4","ch5","same_concept","stated","Both chapters target non-model organisms with little annotation, where marker lists are hard to curate.",["121","123","125"],"high"),
 ("ch8","ch1","same_concept","inferred","Conclusion returns to De Duve's fractionation principle that opens the thesis (introduction, p. 5).",["5","229"],"medium"),
 ("fm-summary","ch2","summarises","inferred","Summary: 'Two chapters ... developing a Bayesian model for spatial proteomics data'.",["vi"],"medium"),
 ("fm-summary","ch3","summarises","inferred","Summary: two chapters on the Bayesian model with dedicated software.",["vi"],"medium"),
 ("fm-summary","ch4","summarises","inferred","Summary: 'application to T. gondii constitutes a massive knowledge expansion'.",["vii"],"high"),
 ("fm-summary","ch5","summarises","inferred","Summary: semi-supervised Bayesian model based on over-fitted mixtures reduces reliance on markers.",["vii"],"high"),
 ("fm-summary","ch6","summarises","inferred","Summary: 'One chapter ... non-parametric context'.",["vii"],"high"),
 ("fm-summary","ch7","summarises","inferred","Summary: Bayesian model for differential localisation experiments.",["vii"],"high"),
]
