# -*- coding: utf-8 -*-
"""Curated per-node metadata: chapter type/template/publication, summaries, quotes (all quotes are checked against the PDF text)."""

CHAPTER_META = {
 "ch1": dict(type="background", template=["Post-genomic motivation","Proteomics and mass spectrometry","Spatial proteomics (3 approaches)","Statistical inference","Thesis outline and contributions"],
             publication_status="Introduction; not stated as published", source_pages=["x"]),
 "ch2": dict(type="method", also=["result"], template=["Motivation (abstract)","Introduction and literature review","Methods (previous methods, model, fitting, prediction)","Comparisons","Case study","Discussion and limitations"],
             publication_status="Published in PLOS Computational Biology (preface, p. x). Edited version of Crook et al. (ref. 83).", collaboration="Co-authors of the paper include Mulvey, Kirk, Lilley and Gatto (ref. 83); the declaration states the thesis is the author's own work except as specified.", source_pages=["x","9"]),
 "ch3": dict(type="method", also=["background"], template=["Motivation (abstract)","Introduction and literature review","Getting started and infrastructure","Methods: TAGM MAP","Methods: TAGM MCMC overview and details","Discussion and limitations"],
             publication_status="Published in F1000 Research (p. x). Edited version of Crook et al. (ref. 84) with significant textual overlap (p. 57).", collaboration="Paper co-authors: Breckels, Lilley, Kirk, Gatto (ref. 84).", source_pages=["x","57"]),
 "ch4": dict(type="result", template=["Motivation (abstract)","Introduction and literature review","Methods and datasets","Results","Discussion and limitations"],
             publication_status="In press at Cell Host and Microbe (p. x). Borrows from Barylyuk et al. (ref. 21).", collaboration="hyperLOPIT experiments by Konstantin Barylyuk; gene editing by Ludek Koreny, Huiling Ke and Simon Butterworth; data analysis by the author and Barylyuk; figures used with Barylyuk's permission (p. 97).", source_pages=["x","97"]),
 "ch5": dict(type="method", also=["result"], template=["Motivation (abstract)","Introduction and literature review","Methods","Results","Comparison with phenoDisco","Endosome case study","Discussion and limitations"],
             publication_status="In press at PLOS Computational Biology (p. x). Edited version of Crook et al. (ref. 81, bioRxiv) with significant textual overlap (p. 123).", collaboration="Paper co-authors include Geladaki, Nightingale, Vennard, Lilley, Gatto and Kirk (ref. 81).", source_pages=["x","123"]),
 "ch6": dict(type="method", also=["result"], template=["Motivation (abstract)","Introduction and literature review","Methods","Results (two case studies, predictive performance)","Discussion and limitations"],
             publication_status="In review at The Annals of Applied Statistics (p. x). Edited version of Crook et al. (ref. 86, arXiv 1903.02909) with significant textual overlap (p. 157).", collaboration="Paper co-authors: Lilley, Gatto, Kirk (ref. 86).", source_pages=["x","157"]),
 "ch7": dict(type="method", also=["result"], template=["Motivation (abstract)","Introduction and literature review","Methods","Results (workflow, simulations, applications, HCMV case study)","Discussion and limitations"],
             publication_status="In preparation for a biological sciences journal; parts published in Proteomics (p. x). Motivation and some concepts published as ref. 82; the majority is in preparation (p. 187).", collaboration="Ref. 82 co-authors: Smith, Elzek, Lilley.", source_pages=["x","187"]),
 "ch8": dict(type="discussion", template=["Summary of principle","Main findings and contributions","Limitations and future work"],
             publication_status="Conclusion; not stated as published", source_pages=["229"]),
 "appA": dict(type="appendix", publication_status="Supplement to chapter 2", source_pages=["269"]),
 "appB": dict(type="appendix", publication_status="Supplement to chapter 6", source_pages=["295"]),
 "appC": dict(type="appendix", publication_status="Supplement to chapter 7", source_pages=["321"]),
}

# summary: short paraphrase of what the author says. quote: (text, page) must occur verbatim in the printed page (or the next).
NODE_META = {
 "fm-summary": dict(summary="Thesis abstract: proteins and why location matters, De Duve's fractionation principle, the limits of classifiers, and a one-paragraph tour of the six research chapters.", quote=("Proteins are biomolecules that govern the biochemical processes of the cell.","vi")),
 "fm-declaration": dict(summary="Original-work declaration; word and figure limits.", quote=("contains fewer than 60,000 words excluding appendices, bibliography, footnotes, tables and equations","v")),
 "fm-dedication": dict(summary="Dedication.", quote=("those that let me stand upon their shoulders","iii")),
 "fm-ack": dict(summary="Thanks to supervisors (Gatto, Kirk, Lilley), the Cambridge Centre for Proteomics and MRC Biostatistics Unit, and collaborators on the Toxoplasma project.", quote=("I am thankful to my supervisors Prof Laurent Gatto, Dr Paul Kirk and Prof Kathryn Lilley","ix")),
 "fm-preface": dict(summary="Publication status of chapters 2-7 (published, in press, in review, in preparation).", quote=("The work presented in this thesis is either published or in preparation for submission to a scientific journal.","x")),
 "fm-toc": dict(summary="Table of contents: source for every structure node in this map."),
 "fm-lof": dict(summary="List of figures (120 entries: 1, 13, 14, 17, 9, 11, 7 in chapters 1-7; 3, 12, 33 in appendices A-C)."),
 "fm-lot": dict(summary="List of tables (49 entries: 1 in ch. 2, 1 in ch. 5, 38 in appendix A, 9 in appendix B). Page headers on the abbreviations pages also read 'List of tables'."),
 "fm-abbrev": dict(summary="Abbreviations list (pp. xxvii-xxix)."),
 "fm-title": dict(summary="Title page: Bayesian methods for spatial proteomics, Oliver McKenzie Crook, Darwin College, University of Cambridge, September 2020."),

 "ch1": dict(summary="Sets the scene: post-genomic proteomics, mass-spectrometry workflows, three kinds of spatial proteomics, why Bayesian inference, and the outline of the thesis.", quote=("Compartmentalisation and localisation are ways of life.","4")),
 "s1.1": dict(summary="The genome-to-function gap: proteoforms outnumber genes, and proteomes vary across cells and time."),
 "s1.2": dict(summary="Proteomics as system-wide study of proteins, and why mass spectrometry became the driving technology."),
 "s1.3": dict(summary="How electrospray ionisation, quadrupole and Orbitrap measurements produce a mass spectrum."),
 "s1.4": dict(summary="Digest-to-peptide workflows and quantification by label-free, TMT and SILAC."),
 "s1.5": dict(summary="Three families of spatial proteomics: microscopy, proximity labelling and fractionation coupled to MS; the thesis focuses on the last.", quote=("Thus determining a protein's subcellular localisation is a key part in the process of pinpointing","4")),
 "s1.5.3": dict(summary="De Duve's centrifugation principle recast as density-gradient or differential-centrifugation MS; powerful but needs heavy analysis and marker proteins.", quote=("relies on marker proteins with localisation known prior to any experimentation","5")),
 "s1.6": dict(summary="Why a Bayesian paradigm: uncertainty, many latent variables, generative models for criticism and simulation."),
 "s1.7": dict(summary="Chapter-by-chapter outline: Bayesian model (2-3), Toxoplasma application (4), novelty detection (5), non-parametric model (6), differential localisation (7).", quote=("The limitations discussed in chapter 2,3 and 4 motivate further extensions of our original","7")),

 "ch2": dict(summary="Introduces the T-augmented Gaussian mixture model (TAGM) for MS spatial proteomics, benchmarks it on 19 datasets against SVM and kNN, and shows what uncertainty quantification adds in a mouse stem-cell case study.", quote=("To our knowledge this is the first Bayesian model of MS-based spatial proteomics data.","10")),
 "s2.1": dict(summary="Abstract of the published paper: classifiers lack uncertainty; a Bayesian generative classifier gives probabilistic assignment."),
 "s2.2": dict(summary="Why localisation matters, how LOPIT/hyperLOPIT work, existing classifiers, and the aims and layout of the chapter.", quote=("half the proteome cannot be robustly assigned to a single sub-cellular location","11")),
 "s2.3": dict(summary="Background on kernel machines, kNN, mixture and Bayesian mixture models, then the TAGM model, its fitting and prediction."),
 "s2.3.1": dict(summary="Review of SVMs/kernels, kNN, Gaussian mixtures, robust mixtures and Bayesian mixture models that TAGM builds on."),
 "s2.3.2": dict(summary="Gaussian component per known niche plus a multivariate-t outlier component with indicator phi; fixed kappa = 4; proper density unlike earlier pseudo-models.", quote=("we extend it by introducing an additional outlier component","27")),
 "s2.3.3": dict(summary="Conjugate Dirichlet, normal-inverse-Wishart and Beta priors; labelled proteins update parameters analytically."),
 "s2.3.4": dict(summary="Predicting unlabelled proteins by EM (MAP) or Monte-Carlo averages of a collapsed Gibbs sampler."),
 "s2.4": dict(summary="Benchmark on 19 datasets with macro-F1 and quadratic loss: no consistent F1 winner, TAGM-MCMC lowest quadratic loss in 16 of 19.", quote=("no single classifier consistently outperforms any other across all datasets","33")),
 "s2.5": dict(summary="mESC hyperLOPIT case study: MAP and MCMC results, proteins the SVM left unassigned (TRIP12, Exportin 5, DOCK6), outlier component enrichment and whole-proteome entropy maps.", quote=("is of paramount importance to understand the molecular basis for pluripotency","39")),
 "s2.6": dict(summary="Summary of uncertainty benefits, roughly 1000 extra informative proteins, and limits: no data integration or explicit multi-localisation, marker reliance, robustness theory not characterised.", quote=("using MCMC based inference our method significantly outperforms the SVM and KNN classifiers","54")),

 "ch3": dict(summary="A step-by-step Bioconductor workflow (pRoloc) for TAGM-MAP and TAGM-MCMC, including convergence checks, chain processing, priors and visualisation.", quote=("There is a clear need for more workflows detailing analysis on specific applications.","61")),
 "s3.1": dict(summary="Abstract of the F1000 workflow paper."),
 "s3.2": dict(summary="Why a Bayesian workflow for biologists, a reminder of TAGM, and an R/S4/Bioconductor primer."),
 "s3.3": dict(summary="Installing pRoloc, MSnbase and pRolocdata; loading the E14TG2a mouse stem-cell LOPIT data."),
 "s3.4": dict(summary="TAGM-MAP by EM: tagmMapTrain, model visualisation with ellipses, convergence of the log-posterior.", quote=("allows for faster inference by using an extended version of the expectation-maximisation (EM) algorithm","63")),
 "s3.5": dict(summary="Overview of MCMC (burn-in, thinning), tagmMcmcTrain / tagmMcmcProcess / tagmPredict outputs."),
 "s3.6": dict(summary="Detailed analysis of a 6-chain run: diagnostics, discarding chains, priors, global and per-protein uncertainty views.", quote=("Assessing whether or not an MCMC algorithm has converged is challenging.","72")),
 "s3.6.3": dict(summary="Empirical-Bayes default priors (prior mean = data mean, lambda0 = 0.01, nu0 = fractions + 2) and Dirichlet prior on weights."),
 "s3.7": dict(summary="Workflow summary; Bayesian uptake among cell biologists is still low; possible future additions (prior/posterior predictive checks).", quote=("the uptake amongst cell biologists is still low","96")),

 "ch4": dict(summary="hyperLOPIT applied to Toxoplasma gondii and analysed with TAGM: 1,916 proteins allocated to 26 niches, validated by gene tagging, then mapped against CRISPR-screen and evolutionary data.", quote=("The spatial proteome of Toxoplasma gondii is poorly characterised and there are few known ground truths","97")),
 "s4.1": dict(summary="Abstract: hyperLOPIT can serve as a discovery tool in poorly annotated organisms; uncertainty quantification suits missing annotations."),
 "s4.2": dict(summary="Apicomplexan biology, Toxoplasma life cycle and organelles (apical complex, rhoptries, micronemes, dense granules, IMC, apicoplast)."),
 "s4.3": dict(summary="Adapted protocol, genomic features (SNP density, dN/dS, CRISPR screen) and validation by endogenous tagging."),
 "s4.3.1": dict(summary="Nitrogen-cavitation lysis, iodixanol density barriers and gradient, TMT10plex fractions."),
 "s4.3.2": dict(summary="62 isolates for SNP/dN/dS data; genome-wide CRISPR-Cas9 phenotype scores."),
 "s4.3.3": dict(summary="CRISPR-Cas9 C-terminal endogenous tagging for immunofluorescence validation (details in ref. 21)."),
 "s4.4": dict(summary="Three experiments, 656 then 718 markers, TAGM-MAP and MCMC, niche resolution, and mapping of CRISPR-screen and selection-pressure features onto the spatial atlas.", quote=("All tested proteins showed subcellular localisation concordant with their hyperLOPIT derived","106")),
 "s4.4.1": dict(summary="t-SNE and HDBSCAN structure; 23 known compartments; 62 tagged proteins all concordant; 1,916 proteins assigned to 26 niches at p > 0.99; MCMC with 9 chains.", quote=("1, 916 proteins with previously unknown localisation were allocated to one of 26 subcellular","111")),
 "s4.4.2": dict(summary="Resolution of 26 compartments and sub-compartments, including sub-organellar splits (mitochondrion, ER, plasma membrane) and two apical clusters."),
 "s4.4.3": dict(summary="Knowledge expansion (795 of the 1,916 were annotated only as hypothetical) and CRISPR-screen / dN/dS / SNP-density patterns by niche.", quote=("Thus, the interpretation that the apicoplast is evolutionary baggage is unsupported","118")),
 "s4.5": dict(summary="First comprehensive apicomplexan spatial proteome; limits: unassigned proteins, low-abundance quantitation, steady-state view; points to novelty detection next.", quote=("This is the first comprehensive and detailed spatial proteome of an apicomplexan cell.","121")),

 "ch5": dict(summary="Novelty TAGM: a semi-supervised Bayesian model using overfitted mixtures to find unannotated sub-cellular niches with uncertainty, applied to 10 datasets and compared with phenoDisco.", quote=("one of the limitations of our Bayesian modelling, thus far, is that it is reliant on marker proteins","123")),
 "s5.1": dict(summary="Motivation (marker reliance) and abstract of the published paper."),
 "s5.2": dict(summary="Why novelty detection helps (validate design, find hidden niches, non-model organisms) and a table of existing methods."),
 "s5.3": dict(summary="Choosing the number of clusters, extending TAGM with up to K_novelty extra components, PSM/PEAR summaries, validation strategy and datasets."),
 "s5.3.1": dict(summary="Frequentist (BIC, AIC), Bayesian and non-parametric ways to choose the number of mixture components."),
 "s5.3.2": dict(summary="Overfitted mixture with K_novelty = 10 and beta_j = 0.5; modified collapsed Gibbs sampler; label switching handled by posterior similarity matrices; discovery probability.", quote=("components that are not supported by the data are left empty with no proteins","133")),
 "s5.3.3": dict(summary="Validation by masking annotations, Human Protein Atlas, GO enrichment with Benjamini-Hochberg control and cross-dataset agreement."),
 "s5.3.4": dict(summary="Ten datasets: hyperLOPIT (mESC, U-2 OS, yeast), LOPIT-DC (U-2 OS), HCMV fibroblast maps, HeLa and neuron DOM data, HEK-293 for phenoDisco."),
 "s5.4": dict(summary="Recovers masked chromatin annotation, finds extra niches in multiple datasets, refines annotations in organelle maps."),
 "s5.4.1": dict(summary="Chromatin enrichment validated: U-2 OS yields 9 and mESC 8 putative phenotypes including chromatin and nucleolus.", quote=("Removing the nuclear, chromatin and ribosomal annotations from the datasets, we test the ability of Novelty TAGM to recover them.","137")),
 "s5.4.2": dict(summary="LOPIT-DC U-2 OS (10 phenotypes, endosome, chromatin), yeast (ER-to-early-Golgi group) and HCMV/mock fibroblasts (ribosomal subunits separated)."),
 "s5.4.3": dict(summary="Dynamic Organellar Maps data: HeLa (3 phenotypes), mouse neurons (10, mostly unenriched), HeLa Hirst (7, 3 singletons)."),
 "s5.5": dict(summary="phenoDisco vs Novelty TAGM on HEK-293: both find 8 phenotypes, 4 vs 5 with GO enrichment; Novelty TAGM adds uncertainty."),
 "s5.6": dict(summary="Re-annotating endosomes in U-2 OS hyperLOPIT; 7 of 240 uncertain proteins all have endosome roles; the HPA agrees or is consistent for 3 of the 4 proteins with annotation."),
 "s5.7": dict(summary="Additional annotation in every dataset; limits: sub-compartment structure and multi-dataset integration remain open.", quote=("revealed additional annotation in every single dataset","155")),

 "ch6": dict(summary="A mixture of Gaussian-process regression models with fast Toeplitz-based computation and HMC, compared with TAGM on five datasets.", quote=("can we develop a model that better reflects the data generating process of the data?","157")),
 "s6.1": dict(summary="Motivation and abstract of the arXiv/AoAS paper."),
 "s6.2": dict(summary="Data-generating process along the density gradient, functional data analysis literature, GP approach."),
 "s6.3": dict(summary="GP regression, marginalising the unknown function, tensor decomposition for fast inversion, HMC hyperparameter inference."),
 "s6.3.4": dict(summary="Covariance has tensor structure; extended Trench and Durbin algorithms speed up inversion."),
 "s6.3.6": dict(summary="Empirical-Bayes or fully Bayesian GP hyperparameters; HMC within Gibbs to handle correlated hyperparameters."),
 "s6.4": dict(summary="Drosophila (labelled vs semi-supervised noise estimates, prior sensitivity), mouse stem cells, and a 5-dataset predictive comparison."),
 "s6.4.1": dict(summary="Semi-supervised hyperparameters shift and shrink noise posteriors relative to labelled-only; hyper-prior sensitivity is minor.", quote=("We observe only minor sensitivity to the choice of hyper-prior","179")),
 "s6.4.2": dict(summary="mESC data fit with GP per niche; MCMC with HMC; entropy and allocation maps."),
 "s6.4.3": dict(summary="GP models beat TAGM in 4 of 5 datasets on quadratic loss; empirical Bayes ties or beats fully Bayesian; TAGM wins on HeLa (Itzhak).", quote=("This is hardly worth the loss in uncertainty quantification","183")),
 "s6.5": dict(summary="Summary, speed-ups (HMC up to 10x more efficient than MH), and pointer to differential localisation.", quote=("most of these modelling tasks would be incremental improvements beyond the methods discussed here","185")),

 "ch7": dict(summary="Defines differential localisation, builds BANDLE, shows by simulation it beats the MR method and applies it to EGF stimulation, AP-4 knockout and HCMV infection.", quote=("which proteins change their resident organelle upon subcellular perturbation?","187")),
 "s7.1": dict(summary="Shift from the allocation problem to the dynamic question; abstract."),
 "s7.2": dict(summary="Dynamic experiments, limits of the MR method and a classification pipeline, and the BANDLE idea.", quote=("these scores can be challenging to interpret","189")),
 "s7.3": dict(summary="MR method, integrative mixture models, BANDLE likelihood, priors, outliers, prior calibration and the differential localisation probability."),
 "s7.3.1": dict(summary="Interpretation of the movement-reproducibility method and review of integrative mixture models."),
 "s7.4": dict(summary="BANDLE workflow, simulations versus MR, EGF and AP-4 applications and a cytomegalovirus case study."),
 "s7.4.1": dict(summary="Workflow: calibrate prior by prior predictive checks, MCMC, convergence checks, rank plots, interpretation against other assays."),
 "s7.4.2": dict(summary="Five simulated scenarios: higher AUC, about twice as many correct re-localisations; MR's chi-squared and p-value assumptions criticised.", quote=("it is inappropriate to cube p-values","206")),
 "s7.4.3": dict(summary="EGF stimulation (MR: 7 hits; BANDLE correlates better with phospho changes) and AP-4 knockout (SERINC1/3 recovered, TMEM199 implicated).", quote=("we hypothesised that proteins with the greatest differential phosphorylation","210")),
 "s7.4.4": dict(summary="HCMV 24 hpi: hundreds of differentially localised proteins; integration with degradation, abundance, acetylation and interactome data; several negative links.", quote=("Perhaps surprisingly, we do not observe increased acetylation levels amongst differentially localised proteins","223")),
 "s7.5": dict(summary="BANDLE gives a differential localisation probability, reduces errors and recovers known biology; limits: PTM level, one comparison at a time, stepwise integration.", quote=("we implicate TMEM199 as potentially overlooked AP-4 cargo","227")),

 "ch8": dict(summary="Summarises contributions chapter by chapter and lists limitations and directions for future work.", quote=("we believe the use of Bayesian modelling will form a key part of the process","229")),
 "s8.1": dict(summary="One-paragraph summary of each research chapter's findings."),
 "s8.2": dict(summary="Twelve limitations and future directions."),
 "s8.2.1": dict(summary="Theory and empirical behaviour of mixed mixtures (robustness) not established."),
 "s8.2.2": dict(summary="Models cannot handle missing values; latent-indicator or restricted-likelihood fixes proposed.", quote=("Our models cannot currently handle missing values.","231")),
 "s8.2.3": dict(summary="Replicates assumed independent; hierarchical sharing needs gradient registration."),
 "s8.2.4": dict(summary="Sub-niche resolution (e.g. ER lumen vs membrane) via mixtures of mixtures; identifiability issues."),
 "s8.2.5": dict(summary="Protein-protein interactions and complexes from spatial profiles would need external validation."),
 "s8.2.6": dict(summary="Computation can be excessive; lower-level code or approximate Bayes could help."),
 "s8.2.7": dict(summary="No integration of different data modalities; multiple dataset integration is suggested."),
 "s8.2.8": dict(summary="Peptide/PSM-level summarisation and uncertainty propagation not explored."),
 "s8.2.9": dict(summary="Localisation of post-translational modifications; Bayesian semi-parametric two-sample test proposed."),
 "s8.2.10": dict(summary="Differential localisation with several perturbations needs a new approach (K^3 parameters naively)."),
 "s8.2.11": dict(summary="Temporal perturbations, e.g. Markov structure on allocations."),
 "s8.2.12": dict(summary="Covariates (space, time, temperature, life-cycle stage) and their independence structure."),

 "refs": dict(summary="Bibliography (496 numbered references)."),
 "appA": dict(summary="Derivations of the EM algorithm and collapsed Gibbs sampler, convergence diagnostics, t-test tables for F1 and quadratic loss, GO enrichment figures.", quote=("This appendix give a formal derivation of the EM algorithm used for our model","269")),
 "appB": dict(summary="Matrix algorithms, derivatives of the marginal likelihood, tensor decompositions, sensitivity analyses, simulation study, HMC vs MH, hyperparameter tables."),
 "appC": dict(summary="Extra BANDLE simulations, convergence analyses, prior sensitivity, selecting tau, EGF/AP-4/HCMV figures and supplementary methods (Pólya-Gamma augmentation).", quote=("A default value of τ = 0.3 appears to work well in practice.","329")),
 "sB.6": dict(summary="HMC is more efficient than Metropolis-Hastings for GP hyperparameter updates (acceptance rate and time-normalised ESS)."),
 "sC.7": dict(summary="Choosing tau for the Pólya-Gamma prior via KL divergence to a weakly informative Dirichlet prior; default tau = 0.3.", quote=("A default value of τ = 0.3 appears to work well in practice.","329")),
 "sC.15": dict(summary="Supplementary methods: non-conjugate prior, Pólya-Gamma and stick-breaking augmentation, correlated differential localisation model, calibration, prior coherence and simulating dynamic experiments."),
}
