# Hand-authored content. Every page number is a PRINTED page (PDF index - 1).
# basis: "stated" = the author says it; "inferred" = my reading.

THESIS = dict(
    title="Developments in Machine Learning and Bonding Indicators for the Quantum Chemical Topology Force Field",
    author="Carlos Outeiral Rubiera",
    degree="Master of Philosophy (MPhil), Faculty of Science and Engineering, University of Manchester",
    year=2018,
    supervisor="P. L. A. Popelier (named in Acknowledgements, p. 16)",
    word_count_stated=42894,
    word_count_source_page=6,
    note="This is an MPhil thesis (one-year research degree, 2017-2018, p. 20), not a PhD.",
)

PAGE_MAP = dict(
    rule="printed page = PDF page index - 1",
    verified_on=244, of=266,
    exceptions=[
        dict(pdf=[1, 2], note="cover and ProQuest notice carry no printed number (treated as p. 0 and p. 1)"),
        dict(pdf=[188, 201], note="embedded journal article: thesis page number not printed; the journal's own pagination 5497-5529 is shown instead. Thesis-counted page = PDF index - 1 (e.g. PDF 189 = p. 188 = Chem. Sci. p. 5517)"),
        dict(pdf=[215], note="OCR misread of the page number; offset is still 1"),
    ],
    numbering="Front matter is arabic-numbered from the cover (no roman numerals).",
    ocr="Scanned PDF: pdftotext returned no text. OCR with tesseract 5 (eng, 220 dpi) page by page; ocrmypdf was not available.",
)

# ---------------------------------------------------------------- summaries
SUMMARY = {
 "front": "Title, notices, contents, abstract, declaration, acknowledgements and acronym list.",
 "front.title": "Title page: MPhil thesis, University of Manchester, 2018.",
 "front.proquest": "ProQuest dissertation notice (number 27614609).",
 "front.contents": "Contents plus lists of tables and figures.",
 "front.abstract": "Sets out FFLUX, three hurdles (polarisation, extrapolation, curse of dimensionality) and two contributions: the delocalization index as a bond-order indicator, and symmetry-adapted kriging in DL_POLY 4.",
 "front.declaration": "Declares no portion submitted for another degree.",
 "front.copyright": "Standard University of Manchester copyright statement.",
 "front.epigraph": "Galileo quotation on mathematics as the language of nature.",
 "front.ack": "Thanks to family, friends and colleagues; EPSRC funding; supervisor P. L. A. Popelier for help getting the Chemical Science article published.",
 "front.acronyms": "Glossary of acronyms (AIM, DI, FFLUX, GP, IQA, QCT, QTAIM and others).",
 "ch1": "Argues force fields, not sampling, limit biomolecular simulation; positions FFLUX (ML-based, Popelier group) as a response; states the open brief and outlines the thesis.",
 "ch2": "Literature review: molecular dynamics and force fields, intermolecular forces, polarisable force fields, Quantum Chemical Topology, Gaussian process regression, and the history of FFLUX.",
 "2.1": "From the Schrödinger equation through Born-Oppenheimer and ab initio MD to classical force-field functional forms.",
 "2.1.1": "Full derivation of the Born-Oppenheimer approximation from the time-dependent Schrödinger equation.",
 "2.1.2": "Born-Oppenheimer and Car-Parrinello molecular dynamics.",
 "2.1.3": "Classical force-field terms (bonds, angles, torsions, Lennard-Jones, point charges, RESP) and their weakness for non-bonded interactions.",
 "2.2": "Theory of intermolecular forces, from van der Waals to perturbation theory and distributed multipoles.",
 "2.2.1": "Historical account: Keesom, Debye and London forces.",
 "2.2.2": "Rayleigh-Schrödinger perturbation theory recovers electrostatic, induction and dispersion terms.",
 "2.2.3": "Cartesian and spherical multipolar expansion of the electrostatic interaction.",
 "2.2.4": "Convergence limits of molecular multipoles; distributed multipoles (Stone DMA, CAMM).",
 "2.3": "Why additive force fields need polarisation, and the three polarisable families.",
 "2.3.1": "Evidence that electronic polarisation errors dominate additive force-field error.",
 "2.3.2": "Fluctuating-charge models based on electronegativity equalisation.",
 "2.3.3": "Classical Drude oscillator model.",
 "2.3.4": "Inducible-dipole models (Applequist, Thole damping, AMOEBA, NEMO).",
 "2.4": "Quantum Chemical Topology: real-space partitioning of the electron density.",
 "2.4.1": "QTAIM: zero-flux atoms, critical points, derivation of atomic observables.",
 "2.4.2": "Interacting Quantum Atoms energy decomposition and its cost.",
 "2.4.3": "IQA for Kohn-Sham DFT via partitioned exchange-correlation energy.",
 "2.4.4": "Topological multipoles: basis-set independent and fast-converging.",
 "2.5": "Machine-learning background for FFLUX's regression engine.",
 "2.5.1": "Derivation of Gaussian process regression (kriging) predictor.",
 "2.5.2": "Hyperparameter training by maximum likelihood, with caveats.",
 "2.5.3": "Global optimisation: gradient descent, basin hopping, particle swarm optimisation.",
 "2.6": "Short history of the Quantum Chemical Topology Force Field.",
 "2.6.1": "From rigid multipolar HF/water simulations to kriging-based flexible multipoles and the first optimisations (water, capped glycine).",
 "ch3": "Presents the FFLUX architecture, force derivations and training pipeline, then critically appraises it through three tests.",
 "3.1": "Potential and features of FFLUX.",
 "3.1.1": "E_FFLUX = E_IQA + E_electrostatic + E_dispersion with kriged atomic energies and multipoles up to hexadecapole.",
 "3.1.2": "Atomic local frame features and rotation matrix.",
 "3.2": "Explicit force expressions.",
 "3.2.1": "Chain-rule derivation of kriging forces through the ALF.",
 "3.2.2": "Derivatives of multipolar interaction tensors for electrostatic forces.",
 "3.3": "The GAIA training pipeline: TYCHE, Gaussian 09, AIMAll, NORMART, FEREBUS, DL_FFLUX.",
 "3.4": "Three limitations of FFLUX, shown by simple numerical tests.",
 "3.4.1": "FFLUX lacks intermolecular polarisation; five-water-cluster test gives ~400 kcal/mol electrostatic error.",
 "3.4.2": "Extrapolation collapse: kriging predictions revert to the mean outside the training set.",
 "3.4.3": "Curse of dimensionality: published capped-glycine model fails on a realistic test set.",
 "3.5": "Summary of the three open challenges.",
 "ch4": "A bond-order study that began as a search for an exchange term for peptide bonds in FFLUX; delocalization indices benchmarked, surveyed over ~200 molecules and applied to exotic bonding.",
 "4.1": "Definition of delocalization and localization indices, link to IQA exchange-correlation, and the Müller approximation.",
 "4.1.1": "Derives DI and LI from the pair density.",
 "4.1.2": "Shows DI is a first-order approximation to V_xc for arbitrary wavefunctions.",
 "4.1.3": "Müller's approximation for correlated 2-RDMs.",
 "4.2": "Computational details, benchmark, correlation effects, bond-order plateaus and subtler effects.",
 "4.2.1": "~200 molecules, HF and CCSD, 6-311++G(2d,2p), Gaussian 09 + AIMAll.",
 "4.2.2": "Benchmark of Müller approximation against full CCSD 2-RDM on 21 small molecules.",
 "4.2.3": "Effect of Coulomb correlation on DIs.",
 "4.2.4": "Plateaus in DI values and k-means clustering.",
 "4.2.5": "Polarity, inductive and resonance effects.",
 "4.3": "DI applied to three exotic bonding cases.",
 "4.3.1": "N8: DI analysis argues against an ionic NBO structure and for pentavalent nitrogen.",
 "4.3.2": "Dilithium cyclopropane with planar tetracoordinate carbon.",
 "4.3.3": "(eta4-C4H6)Fe(CO)3: terminal carbons bind iron more strongly than the central carbon, despite bond path.",
 "4.4": "DI is a reasonable general bond-order indicator.",
 "ch5": "Develops symmetry-adapted kriging to build permutational symmetry into FFLUX models, with a pivot heuristic and DL_FFLUX implementation.",
 "5.1": "Survey of symmetry-adapted features and models.",
 "5.1.1": "Introduction to the two families of approach.",
 "5.1.2": "Behler-Parrinello, bispectrum, SOAP and Coulomb matrices.",
 "5.1.3": "Invariant polynomials and monomial symmetrisation.",
 "5.2": "Group-theoretic derivation of symmetry-adapted kernels.",
 "5.2.1": "Permutation groups and faithful representations.",
 "5.2.2": "Kernel summed over group images; proof of invariance.",
 "5.3": "Pivot-based algorithm and its FFLUX implementation.",
 "5.3.1": "Partition of configuration space into equivalent regions; RMSD-to-pivot projection.",
 "5.3.2": "fflux_symmetry_transformation in DL_POLY FFLUX.",
 "5.4": "Tests on water, ammonia, methanol and acetaldehyde.",
 "5.4.1": "Dissociation curves with MolecularSAGPR.",
 "5.4.2": "Energy minimisations of 6,000 permuted geometries in DL_FFLUX.",
 "5.5": "Conclusions: invariance, six-fold fewer points, minimal code changes.",
 "ch6": "Summarises the DI work and symmetry-adapted kriging as the two contributions. No separate limitations or future-work section.",
 "appA": "The Chemical Science paper and its compound list.",
 "A.1": "Reproduces Outeiral et al., Chem. Sci. 2018, 9, 5517-5529 (journal pagination 5497-5529).",
 "A.2": "List of the ~200 compounds analysed in Chapter 4, grouped by class.",
 "appB": "Fortran listings B.1-B.4 for symmetry transformation, distances, Cartesian conversion and matrix reading.",
 "appC": "Cartesian derivation of multipolar electrostatics up to quadrupole.",
 "C.1": "Interaction between two charge distributions via Taylor expansion.",
 "C.2": "Interaction tensors T up to fourth order.",
 "C.3": "Charge-charge through quadrupole-quadrupole interaction energies.",
 "C.4": "Differences between raw and traceless quadrupole definitions.",
 "C.5": "Rotation of dipoles and quadrupoles between laboratory and local frames.",
 "bib": "331 references.",
}

TYPE = {
 "front": "front", "ch1": "background", "ch2": "background", "ch3": "discussion", "ch4": "result", "ch5": "method", "ch6": "discussion",
 "appA": "appendix", "appB": "appendix", "appC": "appendix", "bib": "appendix",
 "3.1": "method", "3.2": "method", "3.3": "method", "3.4": "result", "3.5": "discussion",
 "4.1": "method", "4.2": "result", "4.3": "result", "4.4": "discussion",
 "5.1": "background", "5.2": "method", "5.3": "method", "5.4": "result", "5.5": "discussion",
}
TYPE_NOTE = {
 "ch3": "Sections 3.1-3.3 present existing FFLUX machinery; section 3.4 holds the author's own tests.",
 "ch4": "Section 4.1 is method; 4.2-4.3 are results.",
 "ch5": "Mostly method/derivation; results in 5.4.",
}

TEMPLATE = {
 "ch1": ["Context", "Problem: force-field accuracy", "ML force fields and FFLUX", "Thesis outline"],
 "ch2": ["Scope", "Molecular dynamics and force fields", "Intermolecular forces", "Polarisable force fields", "Quantum Chemical Topology", "Machine learning", "FFLUX history"],
 "ch3": ["Motivation", "Architecture", "Force formulae", "Training pipeline", "Critical appraisal (three challenges)", "Conclusions"],
 "ch4": ["Motivation", "Theoretical background", "Results and discussion", "Application to exotic bonding", "Conclusions"],
 "ch5": ["Motivation", "Related work", "Derivation", "Efficient algorithm", "Results and discussion", "Conclusions"],
 "ch6": ["Summary of the two developments (no limitations / future-work section)"],
}

QUOTE = {  # node -> (quote, printed page); each checked against the OCR text in validate.py
 "front.abstract": ("This line of research is still in its infancy, and many problems remain unsolved", 11),
 "ch1": ("extend the applicability of the FFLUX force field", 21),
 "ch2": ("reflect the state-of-the-art of computational chemistry in the most sensible way possible", 22),
 "2.2.4": ("divide the molecule into several regions and describe each of these by a set of multipole moments", 46),
 "2.5.1": ("Gaussian process regression is one of the most powerful techniques in machine learning", 71),
 "2.6.1": ("employ machine learning to fit the permanent multipoles of a molecule to its conformational degrees of freedom", 85),
 "ch3": ("what are the main challenges in the development of FFLUX, and how should they be tackled", 87),
 "3.1.1": ("multipole moments are nothing more than the coefficients in a Taylor expansion", 89),
 "3.4": ("these shall not be understood as a criticism to the force field", 100),
 "3.4.1": ("in rigour it can only be categorised as a multipolar force field", 101),
 "3.4.2": ("which we have named extrapolation collapse after encountering it several times", 104),
 "3.4.3": ("the prediction of the kriging models is far less ideal than one would expect", 112),
 "3.5": ("all this challenges constitute open problems in the development of FFLUX", 114),
 "ch4": ("research often starts at a given point and evolves in a completely unexpected dimension", 115),
 "4.1.2": ("the delocalization index is a first-order approximation", 121),
 "4.2.2": ("Most of the DIs for directly bonded atoms show relative errors below 5%", 127),
 "4.2.4": ("bond order is actually a continuous distribution, confirming and then extending Lewis' picture", 133),
 "4.3.1": ("perhaps it only means that new insight should be accepted", 139),
 "ch5": ("increases the robustness and efficiency of atomistic kriging models by implicitly taking into account the symmetries of the system", 145),
 "5.2.2": ("symmetry-adapted kriging is not equivalent to ordinary kriging with projected points", 162),
 "5.3.1": ("instead of projecting the training set to the rest of regions, we will project the prediction point into the training set", 164),
 "ch6": ("ready to be deployed as a tool to fit molecular potentials", 185),
}

PUBLICATION = {
 "ch4": dict(status="published (as Chem. Sci. Edge Article, with additions)", note="Outeiral, Vincent, Martín Pendás, Popelier, Chem. Sci. 2018, 9, 5517-5529; author states he did the vast majority of the calculations and all of the analysis; chapter adds unpublished results (pp. 115, 186).", pages=[115, 186]),
 "A.1": dict(status="published", note="Journal article reproduced; cover artwork designed by the author with help from M. L. Mills (Rhorix) and I. Batalla (p. 186). Co-authors M. A. Vincent, A. Martín Pendás, P. L. A. Popelier (p. 188).", pages=[186, 188]),
 "ch3": dict(status="not stated", note="Appraisal in 3.4 'do[es] not necessarily agree with the vision held currently by the Popelier group' (p. 101). Some results are described as unpublished (p. 109).", pages=[101, 109]),
 "ch5": dict(status="not stated (no publication cited)", note="Implemented in the last version of DL_POLY FFLUX [232]; to be incorporated in the next major version of FFLUX (pp. 165, 181).", pages=[165, 181]),
 "4.2.2": dict(status="partly external compute", note="Full 2-RDM computation ran at MALTA (Oviedo); AIMAll runs at Manchester CSF (p. 127).", pages=[127]),
}

# figure / table caption pages (from the List of Figures + body)
FIG_PAGE = {'2.1':33,'2.2':45,'2.3':46,'3.1':88,'3.2':91,'3.3':99,'3.4':107,'3.5':108,'3.6':108,'3.7':110,'3.8':111,
            '4.1':132,'4.2':134,'4.3':136,'4.4':136,'4.5':138,'4.6':139,'4.7':140,'4.8':142,
            '5.1':147,'5.2':163,'5.3':165,'5.4':166,'5.5':169,'5.6':170,'5.7':171,'5.8':172,'5.9':174,'5.10':175,
            '5.11':177,'5.12':178,'5.13':179}
FIG_NODE = {'2.1':'2.1.3','2.2':'2.2.4','2.3':'2.2.4','3.1':'3.1.1','3.2':'3.1.2','3.3':'3.3','3.4':'3.4.2','3.5':'3.4.2','3.6':'3.4.2','3.7':'3.4.3','3.8':'3.4.3',
            '4.1':'4.2.4','4.2':'4.2.4','4.3':'4.2.5','4.4':'4.2.5','4.5':'4.3.1','4.6':'4.3.1','4.7':'4.3.2','4.8':'4.3.3',
            '5.1':'ch5','5.2':'5.3.1','5.3':'5.3.1','5.4':'5.3.2','5.5':'5.4.1','5.6':'5.4.1','5.7':'5.4.2','5.8':'5.4.2','5.9':'5.4.2','5.10':'5.4.2','5.11':'5.4.2','5.12':'5.4.2','5.13':'5.4.2'}
TAB_NODE = {'2.1':'2.4.1','3.1':'3.4.1','4.1':'4.2.2'}
TAB_PAGE = {'2.1':59,'3.1':103,'4.1':128}
# embedded paper: 8 figures + 1 table (journal Figs 1-8, Table 1) counted under A.1
PAPER_FIGS = {'A.1': 8}; PAPER_TABS = {'A.1': 1}

# ---------------------------------------------------------------- journey
STAGES = [
 dict(id="j1", title="Orientation: the force-field problem and the FFLUX brief",
  question="Why do biomolecular force fields still fail, and how could the group's machine-learned FFLUX force field be extended?",
  approach="Argues force fields, not sampling, limit simulation (p. 19-20); reviews MD, intermolecular forces, polarisable force fields, Quantum Chemical Topology, Gaussian process regression and FFLUX history (Ch. 2).",
  outcome="worked", outcome_note="Background stage: sets scope and tools; no experiment.",
  why_next="FFLUX had reached only single-water and capped-glycine optimisation after a decade (p. 86), so the author asks what the main challenges are before scaling up (p. 87).",
  chapters=["ch1", "ch2"], evidence=[dict(node="ch1", pages=[19, 21]), dict(node="ch2", pages=[22, 85]), dict(node="ch3", pages=[86, 87])],
  basis="stated", confidence="high"),
 dict(id="j2", title="Formalise FFLUX: architecture, forces, training pipeline",
  question="What exactly is FFLUX's potential, how are atomic forces obtained, and how are the kriging models trained?",
  approach="Writes E_FFLUX = E_IQA + E_electrostatic + E_dispersion; defines atomic-local-frame features; derives forces by chain rule through the rotation matrix and the multipole interaction tensors; documents the GAIA pipeline (TYCHE, Gaussian 09, AIMAll, NORMART, FEREBUS, DL_FFLUX).",
  outcome="worked", outcome_note="Presents and derives existing group machinery; numerical verification of the force formulae is referred to ref. [231] (p. 98).",
  why_next="With the formulation written down, the author tests it against three physical and mathematical questions (3.4).",
  chapters=["3.1", "3.2", "3.3", "appC"], evidence=[dict(node="3.1", pages=[87, 93]), dict(node="3.2", pages=[93, 98]), dict(node="3.3", pages=[98, 100]), dict(node="appC", pages=[221, 231], what="derivation of the multipolar electrostatics used in 3.1.1")],
  basis="stated", confidence="high"),
 dict(id="j3", title="Test 1: is intermolecular polarisation negligible?",
  question="Can FFLUX's geometry-only multipoles stand in for polarised electrostatics in a condensed environment?",
  approach="Five snapshots of a 5-water cluster (BP86/Def2SVP BOMD at 600 K, RI-MP2/cc-pVTZ optimisation); compares electrostatic energy from in-vacuo monomer multipoles with energy from cluster multipoles, up to quadrupole, with AIMAll.",
  outcome="failed", outcome_note="Negative result: ~400 kcal/mol electrostatic error, cluster charges shift 0.10 +/- 0.05 e, and conformer ordering is wrong (p. 103). Not fixed; self-consistent polarisation is suggested as future work (p. 104).",
  why_next="Left as an open conceptual limit: FFLUX is 'multipolar' rather than polarisable. Neither Ch. 4 nor Ch. 5 addresses it, and Ch. 6 does not return to it.",
  chapters=["3.4.1"], evidence=[dict(node="3.4.1", pages=[101, 104], what="Table 3.1")],
  basis="stated", confidence="high"),
 dict(id="j4", title="Test 2: what happens outside the training set?",
  question="How does a kriging potential behave when a simulation leaves the region it was trained on?",
  approach="Mathematical argument that the correlation vector goes to zero and the prediction tends to the process mean; single-water model (500 TYCHE points, B3LYP/aug-cc-pVTZ); stretched-bond dissociation curve; Metropolis-Hastings Monte Carlo of 2,500 steps.",
  outcome="failed", outcome_note="Negative result ('extrapolation collapse'): potential goes flat beyond the training range and forces vanish; MC energy stalls at -76.4166 hartree after ~1,000 steps (Fig. 3.5). Two remedies considered and set aside (pp. 108-109).",
  why_next="No simple fix exists, which makes models that cover more of configuration space cheaply attractive; Ch. 5 cites this section as motivation (p. 148).",
  chapters=["3.4.2"], evidence=[dict(node="3.4.2", pages=[104, 109], what="Figs 3.4-3.6")],
  basis="stated", confidence="high"),
 dict(id="j5", title="Test 3: does the model scale to a flexible molecule?",
  question="Do published capped-glycine kriging models give sensible energies on geometries that a finite-temperature simulation would visit?",
  approach="200 RDKit conformers, MMFF94 relaxation and RMSD pruning, 10 lowest kept; B3LYP/apc-1 optimisation plus 200 fs BOMD at 600 K (ORCA) gives 2,000 test geometries; evaluates the published ~0.5 GB model.",
  outcome="failed", outcome_note="Negative result: ~600 kcal/mol mean error, bimodal prediction distribution, minima not ranked (Fig. 3.8). Author blames a 51-dimensional space sampled by about a thousand points and criticises same-method test sets.",
  why_next="Calls for fewer training points and representative test sets (p. 113). Ch. 4 also avoids a two-monomer exchange model because of this problem (p. 116), and Ch. 6 says Ch. 5 was motivated by it (p. 183).",
  chapters=["3.4.3", "3.5"], evidence=[dict(node="3.4.3", pages=[109, 113], what="Fig. 3.8"), dict(node="3.5", pages=[113, 114])],
  basis="stated", confidence="high"),
 dict(id="j6", title="Pivot: from an exchange term for the peptide bond to the delocalization index",
  question="How can FFLUX represent covalent (exchange) interaction between monomers, for example the peptide bond?",
  approach="Rejects a harmonic bond (undoes FFLUX's purpose) and a kriged V_xc (six-dimensional integrals and curse of dimensionality). Proposes the delocalization index as a first-order approximation to V_xc using only 3-D integrals, and proves this for arbitrary wavefunctions; adopts Müller's approximation for correlated 2-RDMs.",
  outcome="pivot", outcome_note="'Soon acquired a dimension of its own' as a bond-order study (p. 116). Suitability of DI as an FFLUX exchange potential is explicitly left as future work (p. 117).",
  why_next="Before using DI anywhere, the author checks the approximation used to compute it (j7) and how DI behaves in ordinary chemistry (j8).",
  chapters=["ch4", "4.1"], evidence=[dict(node="ch4", pages=[115, 118]), dict(node="4.1", pages=[118, 126])],
  basis="stated", confidence="high"),
 dict(id="j7", title="Check Müller's approximation against the full 2-RDM",
  question="Is the Müller approximation accurate enough to compute DIs for correlated wavefunctions?",
  approach="21 small molecules at CCSD/6-311++G(2d,2p): full 2-RDM from pySCF plus PROMOLDEN versus AIMAll's Müller approximation.",
  outcome="partial", outcome_note="Most directly bonded pairs within 5%, but N2 (11.4%), HCN C-N (10.1%) and F2 (34.1%) worse; non-bonded DIs underestimated 20-70% except H-bonds, which are overestimated (Table 4.1). Full 2-RDM took ~2 weeks vs ~10 h.",
  why_next="Accepted as a qualitative tool: HF values serve as the baseline and CCSD/Müller as a lower bound for weak interactions (p. 129).",
  chapters=["4.2.2", "4.1.3"], evidence=[dict(node="4.2.2", pages=[127, 129], what="Table 4.1")],
  basis="stated", confidence="high"),
 dict(id="j8", title="Survey ~200 molecules: does DI behave like a bond order?",
  question="Do delocalization indices reproduce Lewis bond orders and the subtler effects of practical chemistry?",
  approach="~200 organic and inorganic molecules (28 inorganic) at HF and CCSD/6-311++G(2d,2p) with Gaussian 09 and AIMAll; 14,756 HF DI entries; plateau analysis, k-means, HF vs CCSD comparison, homologous series and resonance examples.",
  outcome="worked", outcome_note="DIs cluster near single/aromatic/double values (C-C ~1.0/1.4/1.8), HF is closest to Lewis, correlation lowers bonded DIs and raises weak ones, inductive and resonance effects are recovered; polar bonds fall below formal order.",
  why_next="Having tested only well-known patterns, the author applies DI to disputed exotic bonding (j9).",
  chapters=["4.2.1", "4.2.3", "4.2.4", "4.2.5"], evidence=[dict(node="4.2.1", pages=[126, 127]), dict(node="4.2.3", pages=[129, 131]), dict(node="4.2.4", pages=[131, 134], what="Figs 4.1-4.2"), dict(node="4.2.5", pages=[134, 137], what="Figs 4.3-4.4")],
  basis="stated", confidence="high"),
 dict(id="j9", title="Apply DI to exotic bonding: N8, planar carbon, an iron complex",
  question="Can delocalization indices clarify bonding in disputed or unusual molecules?",
  approach="N8 (EEE and EZE isomers), dilithium cyclopropane (planar tetracoordinate carbon), and (eta4-C4H6)Fe(CO)3 (B3LYP geometry, HF and CCSD single points).",
  outcome="worked", outcome_note="N8: proposes a pentavalent-nitrogen Lewis structure that disagrees with the discoverers' ionic NBO picture; Li2-cyclopropane: no revision needed; Fe complex: total DI ~1.7 consistent with a double bond. Metal complexes otherwise avoided because Müller cannot handle static correlation (p. 141).",
  why_next="Closes the DI thread (published as Chem. Sci. 2018, App. A). The thesis then turns to the sampling problem raised in 3.4 (Ch. 5); Ch. 6 states that link (p. 183).",
  chapters=["4.3.1", "4.3.2", "4.3.3", "4.4", "A.1"], evidence=[dict(node="4.3.1", pages=[137, 140], what="Figs 4.5-4.6"), dict(node="4.3.2", pages=[140, 141]), dict(node="4.3.3", pages=[141, 143]), dict(node="A.1", pages=[186, 186])],
  basis="stated", confidence="high"),
 dict(id="j10", title="Make kriging respect permutational symmetry",
  question="How can a kriging potential recognise that relabelled identical atoms are the same molecule?",
  approach="Reviews symmetry-adapted features and models (5.1); uses finite group theory and faithful representations; builds a kernel summed over group images of each training point; proves invariance by the rearrangement theorem with an isotropic kernel and isometric representations.",
  outcome="partial", outcome_note="Invariance is proven, but in pure form it costs N kernel evaluations per training point, O(NM) (p. 162), and needs FEREBUS changes because symmetry-related weights are shared.",
  why_next="A heuristic is needed to avoid the N-fold cost (j11).",
  chapters=["ch5", "5.1", "5.2"], evidence=[dict(node="ch5", pages=[145, 149], what="Fig. 5.1"), dict(node="5.1", pages=[149, 154]), dict(node="5.2", pages=[154, 162])],
  basis="stated", confidence="high"),
 dict(id="j11", title="Cut the cost: pivot heuristic and DL_FFLUX implementation",
  question="Can symmetry be built in without paying for N kernel evaluations?",
  approach="Splits configuration space into symmetry-equivalent regions; chooses a pivot (usually a PES minimum); applies each representation matrix to the query geometry and keeps the image with minimum Kabsch RMSD to the pivot. Implemented as fflux_symmetry_transformation in DL_POLY FFLUX, leaving feature and force code untouched (App. B).",
  outcome="worked", outcome_note="Cost drops to O(M). The RMSD metric is a heuristic; a metric from first principles is left to future work (p. 165).",
  why_next="Tested on water, ammonia, methanol and acetaldehyde (j12).",
  chapters=["5.3", "appB"], evidence=[dict(node="5.3.1", pages=[162, 165], what="Figs 5.2-5.3"), dict(node="5.3.2", pages=[165, 167], what="Fig. 5.4"), dict(node="appB", pages=[211, 220])],
  basis="stated", confidence="high"),
 dict(id="j12", title="Test on water, ammonia, methanol and acetaldehyde",
  question="Does symmetry-adapted kriging give consistent curves and optimisations when trained on one symmetry region only?",
  approach="Water and NH3 dissociation curves (100 MP2/cc-pVTZ points, MolecularSAGPR on scikit-learn); methanol (600 points) and acetaldehyde (900 points) in DL_FFLUX, TYCHE at 3000 K from one seed; 6,000 test geometries (1,000 x 6 permutations) minimised for 1,500 steps.",
  outcome="worked", outcome_note="All symmetry-adapted runs reach the expected minimum (methanol mean RMSD 0.002 +/- 0.004 A); baseline runs mostly end in wrong structures. One trajectory shows a boundary effect (p. 173). Only one P(3) symmetry centre is tested.",
  why_next="Conclusions (Ch. 6): the method is ready to be deployed and will go into the next FFLUX version (p. 181).",
  chapters=["5.4", "5.5"], evidence=[dict(node="5.4.1", pages=[167, 171], what="Figs 5.5-5.6"), dict(node="5.4.2", pages=[171, 180], what="Figs 5.7-5.13"), dict(node="5.5", pages=[180, 181])],
  basis="stated", confidence="high"),
 dict(id="j13", title="Synthesis: two methodological contributions",
  question="What does the work amount to?",
  approach="Restates the DI work (cheap exchange proxy, Müller validation, bond-order clustering, exotic cases) and symmetry-adapted kriging (group-theoretic kernel plus pivot heuristic).",
  outcome="worked", outcome_note="Polarisation and extrapolation collapse from Ch. 3 are not revisited in Ch. 6; Ch. 1 promises 'future lines of work' (p. 21) but Ch. 6 has no such list.",
  why_next="End of the thesis. Author hands over DI as a bond-order indicator and SAGPR as a tool ready to deploy (p. 185).",
  chapters=["ch6"], evidence=[dict(node="ch6", pages=[182, 185])],
  basis="stated", confidence="high"),
]

ARC = ("The thesis records a one-year MPhil in the Popelier group (2017-2018) whose open brief was to 'extend the applicability of the FFLUX force field' (p. 21). "
       "FFLUX replaces fixed-form valence terms with kriging models of quantum atoms and uses high-order multipoles for electrostatics, but after a decade it had only optimised a single water molecule and capped glycine (p. 86). "
       "The author first audits FFLUX and reports three negative results: no intermolecular polarisation, 'extrapolation collapse' outside the training set, and the curse of dimensionality (Ch. 3). "
       "Two methodological developments follow. The first began as a search for a cheap exchange term to model peptide bonds, then pivoted into a study of the delocalization index as a bond-order indicator, benchmarked on ~200 molecules and published in Chemical Science (Ch. 4). "
       "The second, symmetry-adapted kriging, builds permutational symmetry into the models with a group-theoretic kernel and a pivot heuristic, implemented in DL_FFLUX and tested on four small molecules (Ch. 5). "
       "The polarisation problem is left open. "
       "Order of stages follows the thesis narrative; the author says the path 'might perhaps look sinuous' (p. 21) and gives no dated chronology, so actual order of work is not established.")

CONTRIBUTIONS = [
 dict(text="Critical appraisal of FFLUX with three simple numerical tests: neglected intermolecular polarisation, extrapolation collapse, and the curse of dimensionality.", nodes=["3.4"], pages=[100, 114], basis="stated"),
 dict(text="Delocalization index shown to be a first-order approximation to the exchange-correlation energy for an arbitrary wavefunction, benchmarked (Müller approximation), surveyed over ~200 molecules and applied to exotic bonding; published in Chemical Science 2018.", nodes=["ch4", "A.1"], pages=[115, 186], basis="stated"),
 dict(text="Symmetry-adapted kriging: group-theoretic kernel, pivot heuristic, implementation in DL_POLY FFLUX, tests on four small molecules.", nodes=["ch5"], pages=[145, 181], basis="stated"),
 dict(text="Written derivation of FFLUX atomic forces and a description of the training pipeline (numerical verification cited from earlier work).", nodes=["3.2", "3.3"], pages=[93, 100], basis="stated"),
]

# ---------------------------------------------------------------- claims
def C(i, text, node, stage, pages, fig=None, basis="stated", conf="high"):
    return dict(id=f"c{i:02d}", text=text, node=node, figure=fig, stage=stage, source_pages=pages, basis=basis, confidence=conf)

CLAIMS = [
 C(1, "Very long (>100 microsecond) simulations on special-purpose hardware showed proteins drifting from native structures; the cited authors read this as force fields, not sampling, being limiting.", "ch1", "j1", [19, 20]),
 C(2, "The thesis records the author's 2017-2018 MPhil year in the Popelier group under an open brief.", "ch1", "j1", [20, 21]),
 C(3, "FFLUX (formerly QCTFF) grew from rigid-molecule multipolar simulations of HF and water to kriging-predicted conformation-dependent multipoles, after kriging outperformed neural networks in group comparisons.", "2.6.1", "j1", [84, 85]),
 C(4, "By 2018 FFLUX's maximum demonstrations were optimisations of one water molecule and of capped glycine.", "ch3", "j1", [86]),
 C(5, "Abstract: FFLUX replaces fixed-form valence potentials with non-parametric regression and uses high-order multipolar electrostatics, aiming at ligand-receptor energetics.", "front.abstract", "j1", [11]),
 C(6, "E_FFLUX = E_IQA + E_electrostatic + E_dispersion: E_IQA is a kriged atomic energy, dispersion is Lennard-Jones, electrostatics use kriged multipoles up to hexadecapole.", "3.1.1", "j2", [87, 89], "Fig. 3.1"),
 C(7, "FFLUX assumes charge transfer can be modelled by geometry changes alone.", "3.1.1", "j2", [89]),
 C(8, "Features live in an Atomic Local Frame, removing six translational and rotational degrees of freedom; the frame is set by the heaviest and second-heaviest bonded neighbours (CIP rules for ties).", "3.1.2", "j2", [90, 91], "Fig. 3.2"),
 C(9, "Atomic forces follow from the chain rule through the ALF rotation matrix (internal forces) and through derivatives of the multipole interaction tensors (electrostatic forces); numerical checks are cited from ref. [231].", "3.2", "j2", [93, 98]),
 C(10, "Training runs through GAIA: TYCHE geometries, Gaussian 09, AIMAll integration, NORMART rotation to the ALF, FEREBUS training, then DL_FFLUX.", "3.3", "j2", [98, 100], "Fig. 3.3"),
 C(11, "In FFLUX the charge distribution depends only on molecular geometry, so polarisation is intramolecular only; two same-geometry molecules in different environments get identical multipoles.", "3.4.1", "j3", [101]),
 C(12, "In five water-cluster conformers, using in-vacuo rather than cluster multipoles gave an electrostatic error of about 400 kcal/mol, and cluster charges shifted by 0.10 +/- 0.05 e.", "3.4.1", "j3", [103], "Table 3.1"),
 C(13, "Unpolarised electrostatics cannot rank two conformers: the difference is ~8 kcal/mol with each treatment but of opposite sign (~16 kcal/mol in total); the conclusion rounds this to 'about 20' (p. 114).", "3.4.1", "j3", [103, 114], "Table 3.1", "stated", "medium"),
 C(14, "As features leave the training range the GP prediction tends to the process mean, so the potential is flat and forces are zero ('extrapolation collapse').", "3.4.2", "j4", [105, 106], "Fig. 3.4"),
 C(15, "In a single-water Metropolis-Hastings run, the energy sticks at -76.4166 hartree after ~1,000 of 2,500 steps and the molecule distorts unphysically.", "3.4.2", "j4", [107, 108], "Fig. 3.5-3.6"),
 C(16, "Two remedies are set aside: a feature-dependent mean (classical bond potential) cancels the non-parametric benefit, and dense sampling is costly and often impossible via the curse of dimensionality.", "3.4.2", "j4", [108, 109]),
 C(17, "A published capped-glycine model (~0.5 GB) tested on 2,000 B3LYP/apc-1 BOMD geometries gives a ~600 kcal/mol mean error and does not rank minima.", "3.4.3", "j5", [111, 112], "Fig. 3.8"),
 C(18, "The 51-dimensional feature space is extremely sparse for a training set of about a thousand examples.", "3.4.3", "j5", [112]),
 C(19, "Earlier assessments built test sets by the same method as training sets (selection bias), and published simulations show optimisation to minima but not the energetics along trajectories.", "3.4.3", "j5", [112, 113]),
 C(20, "Three open challenges: neglect of intermolecular polarisation, extrapolation collapse and the curse of dimensionality.", "3.5", "j5", [113, 114]),
 C(21, "In current FFLUX monomers interact only through electrostatics and dispersion, so covalent exchange (e.g. the peptide bond) is missing.", "ch4", "j6", [115, 116]),
 C(22, "Kriging V_xc directly needs six-dimensional integrals over irregular boundaries and models of two monomers' coordinates (curse of dimensionality); a harmonic potential would undo FFLUX's aims; so the DI is proposed as a cheaper proxy.", "ch4", "j6", [116]),
 C(23, "Integrating the exchange-correlation pair density gives N = sum of localization indices plus sum of delocalization indices, splitting an atom's electron pairs into localized and delocalized sets.", "4.1.1", "j6", [119, 120], "Eq. 4.8"),
 C(24, "The DI is a first-order (charge-charge-like) approximation to V_xc for an arbitrary wavefunction and needs 3-D rather than 6-D integrals.", "4.1.2", "j6", [121, 123]),
 C(25, "Müller's approximation estimates the correlated 2-RDM from the 1-RDM; it violates the Pauli principle in general, and p = 0 minimises the violation.", "4.1.3", "j6", [124, 125]),
 C(26, "On 21 small molecules, most directly bonded DIs from CCSD/Müller are within 5% of full-2-RDM CCSD; N2 (11.4%), HCN C-N (10.1%) and F2 (34.1%) are worse; non-bonded DIs are underestimated 20-70% except hydrogen bonds, which are overestimated.", "4.2.2", "j7", [127, 129], "Table 4.1"),
 C(27, "The full CCSD 2-RDM needed ~2 weeks on a 12-CPU node versus ~10 h on 4 cores for AIMAll with Müller.", "4.2.2", "j7", [127]),
 C(28, "HF DIs recover Lewis bond orders (H2 1.000, N2 ~3.04, O2 2.27); CCSD/Müller lowers bonded DIs (H2 0.844, N2 2.310, O2 1.615) and raises weak ones (Ne2 0.005 to 0.009, Ar2 0.002 to 0.015).", "4.2.3", "j8", [129, 130]),
 C(29, "HF and CCSD/Müller DIs correlate strongly (Pearson 0.938 over 1,666 bonds).", "4.2.3", "j8", [130]),
 C(30, "The ~200-molecule database holds 14,756 HF DI entries; C-C DIs plateau near 1.0, 1.4 and 1.8; C-O near 0.8, ~1.2 (aldehydes) and ~1.4 (ketones); weak interactions separate sharply from bonds near 0.5.", "4.2.4", "j8", [131, 133], "Fig. 4.1"),
 C(31, "k-means with three centroids on (DI, distance) pairs recovers the plateaus.", "4.2.4", "j8", [133, 134], "Fig. 4.2"),
 C(32, "DI reflects bond polarity (N2 3.043 vs HCN C-N 2.340), inductive decay along homologous series, and resonance (phenoxide C-O 1.070).", "4.2.5", "j8", [135, 137], "Fig. 4.3-4.4"),
 C(33, "For N8, DIs and QTAIM charges below 0.14 e argue against Hirshberg et al.'s ionic NBO structure and for a pentavalent-nitrogen Lewis structure.", "4.3.1", "j9", [138, 139], "Fig. 4.5-4.6"),
 C(34, "In dilithium cyclopropane (planar tetracoordinate carbon) C-C DIs are 0.98-1.11 and the C-Li DI (0.197) is close to LiH (0.193), so the Li bonds are ionic and no concept needs revising.", "4.3.2", "j9", [140, 141], "Fig. 4.7"),
 C(35, "In (eta4-C4H6)Fe(CO)3, DI(terminal C, Fe) = 0.469 versus 0.292 for the central carbon at HF (0.788 vs 0.286 at CCSD); the total ~1.7 is a double bond, despite no bond path to terminal carbons.", "4.3.3", "j9", [142, 143], "Fig. 4.8"),
 C(36, "The DI is proposed as a general bond-order indicator; whether it works as an FFLUX exchange potential is left as future work.", "4.4", "j9", [117, 143, 144]),
 C(37, "Chapter 4 was published as Outeiral et al., Chem. Sci. 2018, 9, 5517-5529; the author did the vast majority of calculations and all of the analysis.", "A.1", "j9", [115, 186]),
 C(38, "The six permutation-equivalent methanol minima share one Hamiltonian, but ordinary kriging trained on one seed either collapses or optimises to unphysical structures, for example ignoring the rotation barrier.", "ch5", "j10", [146, 148], "Fig. 5.1"),
 C(39, "Prior work uses permutation-invariant features (Behler-Parrinello, bispectrum, SOAP, Coulomb matrices) or invariant models (invariant polynomials).", "5.1", "j10", [149, 153]),
 C(40, "A kernel summed over the group images of each training point gives an invariant GP predictor, proved via the rearrangement theorem, an isotropic kernel and isometric representations.", "5.2.2", "j10", [159, 161], "Eq. 5.22"),
 C(41, "Pure symmetry-adapted kriging needs N kernel evaluations per training point (O(NM)), so it saves nothing by itself.", "5.2.2", "j10", [162]),
 C(42, "Heuristic: map the query into the modelled region by choosing the symmetry image with minimum Kabsch RMSD to a pivot (a PES minimum); cost drops to O(M).", "5.3.1", "j11", [164, 165], "Fig. 5.2-5.3"),
 C(43, "Implemented as fflux_symmetry_transformation in two_body_forces.f90 of DL_POLY FFLUX, reading matrices from MATRICES.txt; feature and force routines unchanged.", "5.3.2", "j11", [165, 166], "Fig. 5.4"),
 C(44, "With 100 MP2/cc-pVTZ points per curve, SAGPR reproduces the stretch of every symmetry-equivalent bond in H2O and NH3, while ordinary GP fails on relabelled bonds.", "5.4.1", "j12", [167, 170], "Fig. 5.5-5.6"),
 C(45, "Methanol (600 training points, 6,000 test geometries): symmetry-adapted minimisations converge to the B3LYP/aug-cc-pVTZ minimum (mean RMSD 0.002 +/- 0.004 A); baseline runs mostly end in wrong structures.", "5.4.2", "j12", [171, 173], "Fig. 5.8-5.10"),
 C(46, "Acetaldehyde (900 training points) shows the same pattern as methanol.", "5.4.2", "j12", [171, 176, 179], "Fig. 5.11-5.13"),
 C(47, "Symmetry adaptation lets the training set shrink about six-fold relative to adding all permuted copies.", "5.5", "j12", [180]),
 C(48, "Conclusions claim DI is proven to be a first-order V_xc approximation, Müller is valid to ~10% for directly bonded atoms, and SAGPR is ready to deploy.", "ch6", "j13", [182, 185], None, "stated", "medium"),
]

# ---------------------------------------------------------------- inferred / semantic edges
def E(src, dst, typ, reason, pages, basis="inferred", conf="medium"):
    return dict(source=src, target=dst, kind="inferred", basis=basis, type=typ, reason=reason, source_pages=pages, confidence=conf)

INFERRED_EDGES = [
 E("ch5", "3.4.3", "answers_limitation", "Ch. 5 is motivated by the curse of dimensionality; Ch. 3 asks for fewer training points and Ch. 6 states the link.", [113, 145, 183], "stated", "high"),
 E("ch4", "3.4.3", "same_concept", "Ch. 4 avoids a kriged two-monomer V_xc because of the curse of dimensionality.", [116], "stated", "high"),
 E("ch4", "3.1.1", "builds_on", "Gap being filled: FFLUX monomers interact only via electrostatics and dispersion.", [88, 89, 115, 116], "stated", "high"),
 E("4.4", "3.1.1", "builds_on", "DI project started as a cheap exchange model for peptide bonds in FFLUX simulations.", [143], "stated", "high"),
 E("3.1.1", "2.4.4", "reuses_method", "FFLUX electrostatics use QTAIM multipoles, citing their convergence and transferability.", [69, 70, 89]),
 E("3.3", "2.5.3", "reuses_method", "FEREBUS trains with particle swarm optimisation, described in 2.5.3.", [83, 99, 100]),
 E("5.2.2", "2.5.1", "builds_on", "Keeps the Gaussian process regression predictor with as few modifications as possible.", [71, 158], "stated", "high"),
 E("5.3.2", "3.2", "reuses_method", "Feature and force subroutines are unchanged by the symmetry code.", [93, 166], "stated", "high"),
 E("5.3.2", "3.1.2", "reuses_method", "Features computed from the ALF after the symmetry transformation.", [89, 166], "stated", "high"),
 E("ch5", "3.1.2", "answers_limitation", "ALF treats the three frame atoms unequally, a stated difficulty for symmetry-adapted kriging.", [146, 155], "stated", "high"),
 E("5.4.2", "3.3", "reuses_method", "Same TYCHE normal-mode distortion sampling and DL_FFLUX engine.", [98, 100, 171]),
 E("4.2.1", "3.3", "reuses_method", "Same Gaussian 09 + AIMAll toolchain used for the DI database.", [99, 126]),
 E("3.4.1", "3.3", "reuses_method", "Uses Gaussian 09 and AIMAll to obtain atomic multipoles for water clusters.", [99, 102, 103]),
 E("3.4.3", "3.4.1", "reuses_method", "Same device to generate test geometries: 600 K BOMD with Berendsen thermostat in ORCA.", [102, 111]),
 E("3.4.2", "3.4.3", "same_concept", "Author says extrapolation collapse is made worse by the curse of dimensionality.", [105, 113], "stated", "high"),
 E("4.2.2", "4.1.3", "builds_on", "Benchmarks the approximation introduced in 4.1.3.", [124, 127]),
 E("4.2.3", "4.2.1", "same_dataset", "Same ~200-molecule HF and CCSD database.", [126, 129]),
 E("4.2.4", "4.2.1", "same_dataset", "Same ~200-molecule database (14,756 HF DI entries).", [126, 131]),
 E("4.2.5", "4.2.1", "same_dataset", "Same database; homologous series and resonance examples.", [126, 134]),
 E("4.3", "4.2", "builds_on", "Applies the DI knowledge from simple molecules to exotic ones.", [137], "stated", "high"),
 E("front.abstract", "3.4", "summarises", "Abstract lists polarisation, extrapolation and dimensionality hurdles.", [11, 100]),
 E("front.abstract", "ch4", "summarises", "Abstract's first contribution is the DI study.", [11, 115]),
 E("front.abstract", "ch5", "summarises", "Abstract's second contribution is symmetry-adapted kriging.", [11, 145]),
 E("ch6", "ch4", "summarises", "Conclusions restate the DI development.", [182, 184], "stated", "high"),
 E("ch6", "ch5", "summarises", "Conclusions restate symmetry-adapted kriging.", [183, 185], "stated", "high"),
 E("A.1", "ch4", "same_content", "Appendix A reproduces the paper on which Ch. 4 is based.", [115, 186], "stated", "high"),
 E("5.1.3", "5.2.2", "same_concept", "Abstract compares the predictor to monomial symmetrisation of invariant polynomials.", [11, 153, 158], "stated"),
 E("5.4.1", "5.2.1", "builds_on", "Uses P(2) and P(3) permutation groups and their representation matrices.", [154, 167, 168]),
 E("3.2.2", "C.2", "builds_on", "Electrostatic forces differentiate the interaction tensors derived in Appendix C.2.", [97, 224]),
]
# bare-number cross-reference ("described in 2.5.2", p. 100) that the 'Section N' regex cannot see
EXTRA_EXPLICIT = [dict(source="3.3", target="2.5.2", type="section_ref", refs=["2.5.2 (no word 'Section')"], source_pages=[100])]

# ---------------------------------------------------------------- source observations
NOTES = [
 dict(id="n1", text="Polarisation error in water clusters is ~16 kcal/mol in total on p. 103 but 'about 20 kcal/mol' on p. 114 (checked on page image).", pages=[103, 114], kind="source inconsistency"),
 dict(id="n2", text="Conclusions say Müller is within a 10% error bound for directly bonded atoms (p. 183); Table 4.1 lists F-F at 34.1% and N-N at 11.4% (p. 128), though the text treats F2 and HF as exceptions.", pages=[128, 183], kind="source inconsistency"),
 dict(id="n3", text="Benzaldehyde C-O DI: thesis p. 137 and the Fig. 4.4 caption give 0.798; the published paper's text gives benzaldehyde 1.297 and 0.798 for propanol (p. 196, checked on page image).", pages=[136, 137, 196], kind="source inconsistency"),
 dict(id="n4", text="Chapter 1 promises that Chapter 6 outlines 'future lines of work' (p. 21); Chapter 6 contains no such list. Future-work remarks are scattered in 3.4, 4 (p. 117) and 5.3.1.", pages=[21, 104, 109, 117, 165], kind="observation"),
 dict(id="n5", text="Pages 187-200 are a copy of the journal paper and carry the journal's pagination (5497-5529); thesis page numbers there are counted, not printed.", pages=[187, 200], kind="page-map caveat"),
]

# ---------------------------------------------------------------- entities
# (id, type, name, regex, description)
ENTITIES = [
 ("e.ffl", "term", "FFLUX / QCTFF", r"FFLUX|QCTFF", "The Quantum Chemical Topology Force Field: kriged atomic energies plus multipolar electrostatics."),
 ("e.qtaim", "method", "QTAIM / quantum atoms", r"QTAIM|Quantum Theory of Atoms|quantum atoms?|atomic basins?", "Real-space atoms from zero-flux surfaces of the electron density."),
 ("e.iqa", "method", "Interacting Quantum Atoms (IQA)", r"\bIQA\b|Interacting Quantum Atoms", "Energy decomposition into atomic self-energies and pair interactions."),
 ("e.qct", "term", "Quantum Chemical Topology", r"Quantum Chemical Topology|\bQCT\b", "Family of real-space partitioning theories."),
 ("e.topomp", "method", "Topological multipoles", r"topological multipoles?|AIM multipoles?|QTAIM multipoles?", "Atomic multipole moments integrated over QTAIM basins."),
 ("e.multipole", "term", "Multipolar electrostatics", r"multipol(?:e|ar)", "Taylor-expansion description of charge-distribution interactions."),
 ("e.polar", "term", "Polarisation", r"[Pp]olari[sz](?:ation|able)", "Response of charge distribution to environment."),
 ("e.gpr", "method", "Gaussian process regression (kriging)", r"kriging|Gaussian [Pp]rocess", "Non-parametric regression used for FFLUX models."),
 ("e.mle", "method", "Maximum likelihood estimation", r"[Mm]aximum likelihood|\bMLE\b", "Hyperparameter training of kriging models."),
 ("e.pso", "method", "Particle swarm optimisation", r"Particle Swarm|\bPSO\b", "Global optimiser used in FEREBUS."),
 ("e.bo", "method", "Born-Oppenheimer approximation", r"Born-Oppenheimer", "Separation of nuclear and electronic motion."),
 ("e.alf", "method", "Atomic local frame (ALF)", r"[Aa]tomic [Ll]ocal [Ff]rame|\bALF\b", "Per-atom coordinate frame that defines FFLUX features."),
 ("e.tyche", "method", "Normal-mode distortion sampling (TYCHE)", r"TYCHE|normal mode distortion", "Generates distorted training geometries."),
 ("e.di", "method", "Delocalization index (DI)", r"delocali[sz]ation ind(?:ex|ices)", "Number of electron pairs shared between two atomic basins."),
 ("e.muller", "method", "Müller approximation", r"M(?:ü|ii|u|d|G)ller", "Approximate 2-RDM built from natural orbitals and occupations."),
 ("e.kmeans", "method", "k-means clustering", r"k-means", "Used to find DI plateaus."),
 ("e.mcmc", "method", "Metropolis-Hastings Monte Carlo", r"Metropolis", "Used for the single-water test of extrapolation collapse."),
 ("e.sagpr", "method", "Symmetry-adapted kriging (SAGPR)", r"symmetry-adapted (?:kriging|Gaussian)|SAGPR", "Thesis's own method for permutational symmetry in GP models."),
 ("e.kabsch", "method", "Kabsch RMSD", r"Kabsch|RMSD", "Distance metric used to pick the symmetry region."),
 ("e.group", "method", "Group theory / faithful representations", r"faithful representation|group theory|permutation group", "Mathematical language for symmetry operations."),
 ("e.hf", "method", "Hartree-Fock", r"Hartree-Fock|\bHF\b", "Baseline electronic structure level."),
 ("e.ccsd", "method", "CCSD", r"CCSD", "Correlated level used for DI comparisons."),
 ("e.dft", "method", "DFT / B3LYP", r"B3LYP|\bDFT\b|Density-Functional", "Density functional methods."),
 ("e.lj", "method", "Lennard-Jones potential", r"Lennard-Jones", "Dispersion term in FFLUX and classical force fields."),
 ("s.g09", "software", "GAUSSIAN 09", r"GAUSSIAN ?09", "Electronic structure program."),
 ("s.aimall", "software", "AIMAll", r"AIMA[Il1]{2}", "QTAIM integration code."),
 ("s.ferebus", "software", "FEREBUS", r"FEREBUS", "Group's parallel kriging engine."),
 ("s.gaia", "software", "GAIA", r"\bGAIA\b", "Perl pipeline automating training-set creation."),
 ("s.dlpoly", "software", "DL_POLY / DL_FFLUX", r"DL[_-]?(?:POLY|FFLUX)", "MD engine with FFLUX implementation."),
 ("s.pyscf", "software", "pySCF", r"pySCF", "Used for full 2-RDMs."),
 ("s.promolden", "software", "PROMOLDEN", r"PROMOLDEN", "QTAIM/IQA code that handles full 2-RDMs."),
 ("s.orca", "software", "ORCA", r"\bORCA\b", "Used for BOMD and optimisations in 3.4."),
 ("s.rdkit", "software", "RDKit", r"RDKit", "Conformer generation for glycine."),
 ("s.sklearn", "software", "scikit-learn / MolecularSAGPR", r"scikit-learn|sci-kit|MolecularSAGPR", "Python implementation for SAGPR dissociation tests."),
 ("d.water5", "dataset", "Five-water cluster conformers", r"five water molecules|cluster of five|5-water", "Five snapshots for the polarisation test."),
 ("d.glycine", "dataset", "Capped-glycine test set (2,000 geometries)", r"capped glycine|glycine", "Test set in 3.4.3."),
 ("d.di200", "dataset", "~200-molecule DI database", r"14,?756|almost 200|~ ?200 molecules|200 molecules", "HF and CCSD DIs for ~200 compounds."),
 ("d.muller21", "dataset", "21-molecule Müller benchmark", r"21 small molecules|21 molecules", "Table 4.1."),
 ("d.methanol", "dataset", "Methanol training/test sets", r"methanol", "600 training points; 6,000 test geometries."),
 ("d.acetald", "dataset", "Acetaldehyde training/test sets", r"acetaldehyde", "900 training points."),
 ("k.extrap", "term", "Extrapolation collapse", r"extrapolation collapse", "GP prediction reverts to the mean outside the training set."),
 ("k.curse", "term", "Curse of dimensionality", r"curse of dimensionality", "Exponential growth of sampling needs with dimension."),
 ("k.kqa", "term", "Knowledgeable quantum atoms", r"knowledgeable quantum atoms", "FFLUX's atom-by-atom kriging model concept."),
 ("k.perm", "term", "Permutational symmetry", r"permutational (?:symmetry|invariance)|permutationally", "Invariance to relabelling identical atoms."),
 ("k.bondorder", "term", "Bond order / Lewis picture", r"bond order|Lewis", "Classical bond-order concept that DI revisits."),
 ("k.n8", "term", "N8 molecule", r"\bN[8g]\b", "Polynitrogen molecule studied in 4.3.1."),
 ("k.ptc", "term", "Planar tetracoordinate carbon", r"planar tetracoordinate", "Studied in 4.3.2."),
 ("k.fe", "term", "(eta4-C4H6)Fe(CO)3 complex", r"Fe\(CO\)|organometallic", "Studied in 4.3.3."),
]

# ---------------------------------------------------------------- figures and tables as leaf nodes
FIG_TITLE = {
 '2.1': "Morse potential for H2", '2.2': "Spheres of divergence in the water dimer",
 '2.3': "Distributed versus molecular multipoles in the benzene dimer",
 '3.1': "Scheme of interactions in the FFLUX force field", '3.2': "Definition of an atomic local frame",
 '3.3': "Scheme of the training pipeline", '3.4': "Dissociation curve of water as computed by FFLUX",
 '3.5': "Energy along a single-water Monte Carlo simulation", '3.6': "First and last snapshots of the 2,500-step water simulation",
 '3.7': "The curse of dimensionality, pictorially", '3.8': "Energies in glycine: B3LYP/apc-1 versus FFLUX",
 '4.1': "Distribution of HF delocalization indices", '4.2': "k-means clustering of internuclear distance versus DI",
 '4.3': "Decay of the DI in the alcohols and aldehydes series", '4.4': "Resonance structures: benzaldehyde, phenol, phenoxide",
 '4.5': "Lewis structure of the N8 molecule", '4.6': "Calculated DIs of the N8 molecule",
 '4.7': "DIs for the dilithium-substituted cyclopropane", '4.8': "DIs for (eta4-C4H6)Fe(CO)3",
 '5.1': "Permutationally equivalent conformers of methanol", '5.2': "Diagram of the symmetry partition scheme",
 '5.3': "Diagram of the symmetry algorithm", '5.4': "Symmetry projection in FFLUX",
 '5.5': "Dissociation curve of H2O: GP versus SAGPR", '5.6': "Dissociation curve of NH3: GP versus SAGPR",
 '5.7': "Training set for methanol and acetaldehyde", '5.8': "Evolution of methanol simulations",
 '5.9': "Methanol permuted conformers without symmetry", '5.10': "Methanol permuted conformers with symmetry",
 '5.11': "Evolution of acetaldehyde simulations", '5.12': "Acetaldehyde permuted conformers without symmetry",
 '5.13': "Acetaldehyde permuted conformers with symmetry",
}
TAB_TITLE = {'2.1': "Classification of critical points of the electron density",
             '3.1': "Electrostatics of a cluster of five water molecules",
             '4.1': "Benchmark of the Müller approximation against the full 2-RDM"}
# embedded journal paper (thesis-counted pages; journal figure numbers)
PAPER_FIG = {  # label: (title, thesis page, journal page)
 'J1': ("Quantum atoms in the N8 molecule", 189, 5518), 'J2': ("Distribution of HF delocalization indices", 194, 5523),
 'J3': ("k-means clustering, distance versus DI", 195, 5524), 'J4': ("Resonance canonicals: benzaldehyde, phenol, phenoxide", 196, 5525),
 'J5': ("Lewis structures of N8", 196, 5525), 'J6': ("Optimized N8 isomers with DIs", 197, 5526),
 'J7': ("Dilithium cyclopropane with DIs", 197, 5526), 'J8': ("(eta4-C4H6)Fe(CO)3 geometry with DIs", 198, 5527)}
PAPER_TAB = {'J1': ("Comparison of DIs at HF, CCSD/Müller and CCSD", 193, 5522)}
