"""Journey, claims, entities, inferred edges, anomalies. Page numbers are PRINTED page numbers.
basis='stated'   -> the author says it (possibly paraphrased here)
basis='inferred' -> my reading across passages; reason given."""

ORDER_NOTE = ("Stage order follows the thesis' own narrative order (Ch 2 -> Ch 5). The thesis does not give a research timeline; the only "
              "stated sequence is Ch 3 before Ch 4 (Ch 4 reuses the Ch 3 model and metrics, pp. 89, 97). Treat the sequence as narrative, not chronological.")

ORIGIN = dict(
    id='j0', title="Start: make ML reliable in early drug discovery",
    question="Drug discovery fails often and is costly; can deep learning improve the quality of candidates entering trials? To do so a model must master intramolecular bonding (valid molecules) and intermolecular binding, and structure-based work needs an accurate target structure.",
    chapters=['ch1'], nodes=['s1.1', 's1.4', 's1.5'], evidence=['3', '4', '5', '30', '31'], basis='stated', confidence='high')

STAGES = [
 dict(id='j1', title="Build a debiased scoring function (PointVS)",
  question="Can an ML scoring function stay competitive when training data are filtered so the test proteins and ligands have no close analogues in training?",
  approach="PointVS: 48-layer E(n)-equivariant GNN with learned edge attention, pretrained on pose classification (Redocked2020) then fine-tuned on PDBBind General affinities. Training sets filtered at Morgan Tanimoto >0.8 / sequence identity >0.8 to the test set, with size-matched random subsets as control.",
  outcome='partial', negative_result=False,
  outcome_note="Pose ranking barely changed with filtering (Top-1 70% to 68%). Affinity PCC fell from 0.805 to 0.754 with filtering but not with equal-size random removal (0.803), so standard CASF16 numbers are inflated by leakage (284 of 285 Core proteins have a >=90%-identity training counterpart). Debiased PointVS (0.754) still beat AutoDock Vina (0.601). Largely Scantlebury's work (p. 35).",
  why_next="Good performance when debiased is only circumstantial evidence that interactions are learned; a more direct test is to look at what the model attributes its score to (p. 52).",
  next='j2', chapters=['ch2'], nodes=['s2.3', 's2.4.1', 's2.4.2', 's2.4.3', 's2.5.1', 's2.5.1.1', 's2.5.1.2'],
  evidence=['35', '37', '38', '41', '49', '50', '51', '52'], basis='stated', confidence='high'),
 dict(id='j2', title="Check it uses real interactions (attribution)",
  question="Does PointVS base its predictions on genuine protein-ligand interactions rather than dataset patterns?",
  approach="Compare edge-attention attribution (PointVS), bond masking (IGN) and atom masking (gnina) against PLIP interactions on three Tankyrase-2 complexes, and correlate attribution scores with protein-ligand distance over the PDBBind Core set and a 20-structure subset.",
  outcome='worked', negative_result=False,
  outcome_note="PointVS ranked PLIP hydrogen-bond edges first and second in all three complexes but missed one halogen bond; gnina and IGN agreed much less. Author's own wording is cautious: 'at least partial agreement' (p. 34).",
  why_next="If attribution finds important protein atoms in one structure, averaging over many bound fragments should expose hotspots usable as design constraints.",
  next='j3', chapters=['ch2'], nodes=['s2.4.4', 's2.5.2', 's2.5.2.1', 's2.5.2.2'],
  evidence=['34', '52', '55', '56', '57'], basis='stated', confidence='high'),
 dict(id='j3', title="Turn hotspots into fragment elaboration",
  question="Can attribution-derived hotspots from fragment screens guide fragment elaboration better than a data-driven hotspot method?",
  approach="Run edge-attention attribution on bound fragment structures (Mpro 152, Mac1 58, NSP14 19), average per protein atom, feed top hotspots to STRIFE, dock elaborations with GOLD and compare standardised ligand efficiency (ΔSLE20) with Hotspots API hotspots. Controls: PLIP contact counts and random subsets of 10-80 structures. FGFR1 case study in Appendix A.4.",
  outcome='worked', negative_result=False,
  outcome_note="Top-5 PointVS hotspots gave higher ΔSLE20 than top-5 API hotspots on all three targets (e.g. Mpro 0.341 vs 0.213). API hotspots ranked 6-10 scored higher, but the API could not rank its hotspots whereas PointVS ranking separated good from worse. Evaluation is by docking score only.",
  why_next="Fragment-based design needs good structural and fragment data; where that is missing, or broader chemical space is wanted, de novo design with diffusion models is the next step, and its main weakness is plausibility (p. 63).",
  next='j4', chapters=['ch2'], nodes=['s2.4.5', 's2.5.3', 's2.5.3.1', 's2.5.3.2', 's2.5.4', 's2.6', 'sA.4'],
  evidence=['59', '60', '61', '62', '63', '133', '134'], basis='stated', confidence='high'),
 dict(id='j4', title="Find a recipe for negative training data",
  question="If distorted molecules are added to the training set as labelled negatives, how many and how distorted should they be?",
  approach="Ablation with EDM on GEOM (no H): distorted:original ratios 1:20, 1:50, 1:100 and maximum distortions 0.1-1 Å; the label is the distortion D; sample at D = 0 and, for contrast, at D = Dmax (100 molecules each).",
  outcome='worked', negative_result=False,
  outcome_note="Best: 1:50 with Dmax = 0.25 Å (RDKit 97%, PoseBusters 81%). Too little distortion blurs the label; too much stops the model learning subtle flaws (1:100 at 1 Å: 8%). Sampling at D = Dmax gave at most 53%, showing the label carries information.",
  why_next="Apply the chosen setting (1:50, 0.25 Å) to QM9, GEOM and ZINC.",
  next='j5', chapters=['ch3'], nodes=['s3.3.2', 's3.4.1', 'sB.1'],
  evidence=['72', '76', '77', '78', '137'], basis='stated', confidence='high'),
 dict(id='j5', title="Condition EDM on distortion across datasets",
  question="Does sampling from the low-distortion region improve the physical plausibility of EDM molecules across small and drug-like datasets?",
  approach="Train EDM conditionally on distorted QM9, GEOM and a ZINC subset; sample 1000 molecules at D = 0 and score with RDKit sanitisation and PoseBusters.",
  outcome='worked', negative_result=True,
  outcome_note="PoseBusters pass rate rose on GEOM (62.2 to 68.8%) and ZINC (40.0 to 74.5%) but fell on QM9 (81.1 to 46.9%). The author reads this as the method helping where molecules are larger and conformational space more complex, and EDM already suiting QM9 (pp. 78-79, 84).",
  why_next="Distortion distance is a crude label; test a physically grounded one, XTB internal energy.",
  next='j6', chapters=['ch3'], nodes=['s3.4', 's3.4.2'], evidence=['78', '79', '84', '85'], basis='stated', confidence='high'),
 dict(id='j6', title="Try internal energy as the label",
  question="Would an XTB internal-energy label work better than a distance-based distortion factor?",
  approach="Annotate original and distorted molecules with GFN2-xTB single-point energies, train conditionally, and sample at each dataset's lowest energy (100 molecules per model).",
  outcome='partial', negative_result=True,
  outcome_note="Best single result on GEOM (RDKit 98%, PoseBusters 84% vs 90% / 70% baseline) but much worse on QM9 (19%) and slightly worse than baseline on ZINC (36% vs 40%). The thesis' explanation, offered as likely rather than shown: energies are hard to compare across different molecules (p. 81).",
  why_next="Keep the simpler distance label as the main method and test whether it transfers to other generative architectures.",
  next='j7', chapters=['ch3'], nodes=['s3.4.3'], evidence=['80', '81', '82'], basis='stated', confidence='high'),
 dict(id='j7', title="Test transfer to GCDM and MolFM",
  question="Does distortion conditioning work for other plausibility-oriented generators?",
  approach="Apply the same conditioning to GCDM (geometry-complete diffusion) and MolFM (flow matching) on GEOM and ZINC.",
  outcome='partial', negative_result=True,
  outcome_note="GCDM: large gain on ZINC (PoseBusters 40.8 to 66.5%), marginal on GEOM. MolFM: worse on GEOM (80.8 to 46.8%), slightly better on ZINC. The cause is 'unclear' (p. 83). Note: Appendix B.2's MolFM GEOM rows disagree with Table 3.5 (see anomalies).",
  why_next="Having refined the training data, tackle plausibility from the generation side: build molecules from pre-validated fragments rather than atoms (p. 84).",
  next='j8', chapters=['ch3'], nodes=['s3.4.4', 's3.5', 'sB.2', 'sB.3'], evidence=['82', '83', '84', '85', '138'], basis='stated', confidence='high'),
 dict(id='j8', title="Replace atoms with blocks: centroid-only",
  question="Is placing individual atoms in 3D the reason diffusion models generate implausible molecules, and would BRICS fragment blocks (also helping synthesisability) make the task tractable?",
  approach="Adapt the Ch 3 EDM so each node is a BRICS block with a centroid position and a block-type one-hot (172 types from GEOM; 56,281 molecules); rebuild atoms from an RDKit conformer per block. Test centroid-only, then a plane-alignment post-process.",
  outcome='pivot', negative_result=True,
  outcome_note="Even with ground-truth blocks and centroids only 48 of 100 molecules passed RDKit, so the representation itself caps performance; the generative model reached about 4%. Plane alignment gave 10.8%, failing on inter-block connectivity.",
  why_next="Orientation cannot be fixed by post-processing; it must be learned, so add explicit orientation vectors (p. 98).",
  next='j9', chapters=['ch4'], nodes=['s4.2', 's4.3.1.2', 's4.3.2.2', 's4.4.1', 's4.4.2'], evidence=['88', '89', '92', '93', '97', '98'], basis='stated', confidence='high'),
 dict(id='j9', title="Add orientation vectors to blocks",
  question="Can a richer position-plus-orientation descriptor close the gap to atomistic diffusion?",
  approach="Describe each block by three 3D vectors (centroid, best-fit-plane normal, in-plane axis) and train on full BRICS (172 types) and a reduced library (23 canonical rings and atoms; 62,746 molecules).",
  outcome='failed', negative_result=True,
  outcome_note="Reconstruction control rose from 48 to 89 of 100, and generation reached 27.2% (full) and 51.7% (reduced) RDKit sanitisation, but not the 84.7% of the atomistic model. The thesis diagnoses geometric variance of BRICS fragments, which blocks a consistent local frame.",
  why_next="Later work (HierDiff, CMD-GEN) uses learned equivariant decoders or hierarchy and works; the thesis recommends that route and does not pursue it. The work then turns to the structure-prediction side, which the Introduction called a prerequisite for structure-based design (p. 5).",
  next='j10', chapters=['ch4'], nodes=['s4.3.2.3', 's4.4.3', 's4.5', 's4.6'], evidence=['93', '95', '99', '100', '101', '102'], basis='stated', confidence='high'),
 dict(id='j10', title="Condition OpenFold on a cryo-EM map",
  question="Can a map-overlap gradient inside OpenFold's structure module pull a poor prediction towards the experimental density?",
  approach="Simulate a density map from the prediction, take dot-product overlap with the (simulated) target map, back-propagate to coordinates, frames or single representation, and add a scaled update; test constant scaling, three decay schedules and iterative or adaptive updates on 10 monomer targets.",
  outcome='pivot', negative_result=True,
  outcome_note="Gains were modest and inconsistent; frame-level conditioning did nothing at constant scaling; 7VPL and 8CXO got worse in every setting; the best scheme improved 9 of 10 targets but 'all improvements were marginal' (p. 116). Larger updates collapsed structures.",
  why_next="Late intervention cannot make large rearrangements without breaking learned priors; try diffusion-based Boltz-2, which tolerates perturbation better (p. 116).",
  next='j11', chapters=['ch5'], nodes=['s5.3.1', 's5.3.3', 's5.4.1', 's5.4.1.1', 's5.4.1.2', 's5.4.1.3'], evidence=['107', '111', '112', '114', '116'], basis='stated', confidence='high'),
 dict(id='j11', title="Move the idea to Boltz-2",
  question="Does a diffusion-based predictor accept stronger map guidance without structural collapse?",
  approach="Apply the same gradient-based optimisation inside the Boltz-2 structure module at each diffusion step.",
  outcome='partial', negative_result=False,
  outcome_note="Large rearrangements became possible (8FEI 20.0 to 2.4 Å, 8CXO 11.7 to 7.7 Å) and 5YW7, 6LN8, 7N70 improved, but 6LLY and 7VLR got worse; the author calls it not yet reliable (p. 118).",
  why_next="Inconsistency suggested that intervening late in the pipeline is insufficient; intervene earlier by subsampling MSAs, as ROCKET and CryoBoltz suggest (p. 119).",
  next='j12', chapters=['ch5'], nodes=['s5.4.2', 's5.4.2.1'], evidence=['116', '117', '118', '119'], basis='stated', confidence='high'),
 dict(id='j12', title="Inject stochasticity with MSA subsampling",
  question="Can early stochasticity let Boltz-2 escape the local minima of its unconstrained prediction and reach conformations closer to the map?",
  approach="Run five parallel Boltz-2 predictions from MSAs sampled at 8192, 4096 or 2048 sequences, prune the worst trajectory every 20 steps, with and without gradient conditioning.",
  outcome='partial', negative_result=True,
  outcome_note="MSA subsampling alone helped 7VLR and 7VPL but was inconsistent. Combined with gradients it was the best approach tried, excluding 8FEI (which got worse); 2048 sequences gave the lowest RMSD on only 6 of 10 targets. All results use simulated maps and ground-truth alignment (pp. 110-111, 122).",
  why_next="End of the experimental work: sample more MSAs, repeat runs, add noise injection, then drop ground-truth alignment and move to real experimental maps (p. 122).",
  next=None, chapters=['ch5'], nodes=['s5.3.2', 's5.4.2.2', 's5.4.2.2~only-msa-subsampling', 's5.4.2.2~combining-with-gradient-based-optimisation', 's5.5'], evidence=['110', '111', '119', '120', '121', '122'], basis='stated', confidence='high'),
]

DESTINATION = dict(
    id='j13', title="Where it ends up",
    question="What does it amount to?",
    approach="Chapter 6 gives per-application conclusions and four lessons.",
    outcome_note="Chapter 6 states that none of the methods is a complete solution, but each gives insight into how data quality, architecture and conditioning shape outcomes (p. 126).",
    chapters=['ch6'], nodes=['s6.1', 's6.2', 's6.3', 's6.4'], evidence=['123', '124', '125', '126'], basis='stated', confidence='high')

ARC = ("The thesis starts from the cost and high failure rate of drug discovery and asks how machine learning can make the early stages more reliable. "
       "It first tests whether a scoring function can avoid memorising dataset bias: PointVS is trained on filtered data, shown to rely on interactions that agree with an interaction profiler, and its attributions are turned into hotspots that improve fragment elaboration. "
       "It then moves to generating molecules with diffusion models. Adding distorted molecules as labelled negatives raises the physical plausibility of drug-like samples, but not for the smallest molecules or for flow matching, and an energy label is no better than a simple distance label. "
       "A second attempt to simplify generation by assembling molecules from fragment blocks fails to match atomistic models because fragment orientation cannot be encoded consistently. "
       "The last project conditions AlphaFold-family predictors on cryo-EM density: late-stage gradient updates in OpenFold stall, Boltz-2 tolerates more, and MSA subsampling adds the early stochasticity needed, with results that stay mixed and rest on simulated maps. "
       "The thesis ends with lessons about interpretability, negative data, block-based encodings and early intervention, and an explicit call for better datasets and benchmarks.")

CONTRIBUTIONS = [
 dict(text="Showed that the CASF16 benchmark leaks (284/285 Core proteins have a >=90%-identity training counterpart) and built PointVS, a scoring function trained and tested on filtered data (shared with J. Scantlebury).", chapters=['ch2'], pages=['49', '62'], basis='stated', stage='j1'),
 dict(text="First ML-based method, per the author, for extracting structural information from a protein target in a way that is useful for fragment elaboration: attribution-derived hotspots gave better top-5 docking efficiency than the Hotspots API. (Priority claim is the author's; not checked externally.)", chapters=['ch2'], pages=['61', '62'], basis='stated', stage='j3'),
 dict(text="Quality conditioning: adding distorted molecules as labelled negatives raises PoseBusters validity of EDM and GCDM samples on drug-like datasets.", chapters=['ch3'], pages=['83', '84', '124'], basis='stated', stage='j5'),
 dict(text="A documented negative result for BRICS block diffusion, with a diagnosis (orientation ambiguity, fragment geometric variance) and a pointer to hierarchical decoders.", chapters=['ch4'], pages=['101', '102'], basis='stated', stage='j9'),
 dict(text="A map of which cryo-EM conditioning strategies for OpenFold and Boltz-2 do not work, plus an MSA-subsampling route for Boltz-2; the author says the work clarifies ineffective strategies more than it finds a viable one.", chapters=['ch5', 'ch6'], pages=['122', '126'], basis='stated', stage='j12'),
 dict(text="Four lessons: interpretability is central; negative data strengthens generative models; block generation needs sophisticated encodings; guiding AlphaFold-like predictors needs early intervention plus stochasticity.", chapters=['ch6'], pages=['126'], basis='stated', stage=None),
]

# ------------------------------------------------------------------------ claims
def C(i, text, node, stage, pages, ref=None, basis='stated', conf='high', quote=None):
    return dict(id=i, text=text, node=node, stage=stage, pages=pages, evidence=ref, basis=basis, confidence=conf, quote=quote)
CLAIMS = [
 C('c1', "Median cost of bringing a drug to market is about $1.3bn and takes over ten years on average.", 's1.1', 'j0', ['3'], None),
 C('c2', "Lack of efficacy is the main cause of failure in over 50% of Phase II and over 60% of Phase III cases; safety accounts for about 20-25%.", 's1.1', 'j0', ['3', '4'], None),
 C('c3', "In the original DUD, 42% of actives were charged versus 15% of decoys, letting models inflate performance by labelling charged compounds active.", 's1.4.2', 'j0', ['26'], None),
 C('c4', "Joint first-author split: Scantlebury designed PointVS and did dataset filtering and scoring-function assessment; Vost did the other attribution methods, the attribution tests and the elaboration tests.", 's2.2', 'j1', ['35'], None),
 C('c5', "284 of 285 PDBBind Core proteins have a counterpart with ≥90% sequence similarity in the General set; 273 (95.7%) have an identical sequence.", 's2.5.1.1', 'j1', ['49'], None),
 C('c6', "Pose ranking is barely affected by filtering: Top-1 on gninaSetPose is 70% (Redocked) and 68% (Redocked\\gninaSetPose80); gnina trained on Redocked gets 68%.", 's2.5.1.2', 'j1', ['50'], 'Fig 2.3'),
 C('c7', "Core-set Top-1 without the crystal pose: PointVS 85.3% (Redocked), 84.2% (Redocked\\Core80); Vina 84.6%; gnina 83.2%.", 's2.5.1.2', 'j1', ['51'], 'Table 2.3'),
 C('c8', "Scoring power (PCC): PointVS General 0.805, General\\CoreR 0.803, General\\Core80 0.754; Vina 0.601; debiased X-Score 0.631. Equal-size random removal does not reduce performance, filtering does.", 's2.5.1.2', 'j1', ['51', '52'], 'Table 2.4'),
 C('c9', "In three Tankyrase-2 complexes PointVS ranks the PLIP hydrogen-bond edges first and second; it misses the halogen bond in 4J21. IGN bond masking found none of the hydrogen bonds; gnina atom masking identified an important bond in only one structure.", 's2.5.2.1', 'j2', ['54', '55'], 'Fig 2.4'),
 C('c10', "Attribution score correlates negatively with protein-ligand atom distance over the Core set: PCC -0.766 (top 5) and -0.844 (top 10).", 's2.5.2.2', 'j2', ['56'], None),
 C('c11', "On 20 Core structures, PointVS top-5 / top-10 PCC is -0.710 / -0.853 versus gnina -0.233 / 0.094.", 's2.5.2.2', 'j2', ['57'], 'Table 2.5'),
 C('c12', "PLIP counting yields four Mpro hotspots (146, 40, 9, 5 of 152 structures). All but one lie within 2 Å of a top-5 PointVS hotspot, yet PointVS ranks the 146-count atom second and the 40-count atom first.", 's2.5.3.1', 'j3', ['58', '59'], 'Fig 2.5'),
 C('c13', "With as few as 10 bound structures the full-screen top-5 PointVS hotspots are still the most commonly picked; consistency rises with more structures (sizes 10-80, 40 random draws each).", 's2.5.3.2', 'j3', ['60'], 'Fig 2.6'),
 C('c14', "Top-5 PointVS hotspots gave higher ΔSLE20 than top-5 API hotspots on all three targets: Mpro 0.341 vs 0.213, Mac1 1.749 vs 1.581, NSP14 1.708 vs 1.240.", 's2.5.4', 'j3', ['61'], 'Table 2.7'),
 C('c15', "API hotspots ranked 6-10 had higher ΔSLE20 than PointVS 6-10 on all three targets, but PointVS ranks 1-5 beat 6-10 while the API could not rank its hotspots.", 's2.5.4', 'j3', ['61'], 'Table 2.7'),
 C('c16', "Elaborations are judged by GOLD constrained-docking score per heavy atom, standardised against the ground-truth molecule (ΔSLE20); no experimental testing is reported in the chapter.", 's2.4.5.5', 'j3', ['48'], None, basis='inferred', conf='medium'),
 C('c17', "FGFR1 case study: PointVS ranks both hydrogen-bonding protein atoms of erdafitinib 3rd and 6th; the Hotspots API places a donor hotspot 1.5 Å from one but misses the other.", 'sA.4', 'j3', ['133', '134'], None),
 C('c18', "Best ablation setting on GEOM (no H): 1 distorted per 50 originals, Dmax 0.25 Å, giving RDKit 97% and PoseBusters 81% (n = 100).", 's3.4.1', 'j4', ['77', '78'], 'Table 3.1'),
 C('c19', "1:100 at Dmax = 1 Å gives PoseBusters 8%; sampling at D = Dmax yields at most 53%.", 's3.4.1', 'j4', ['78'], 'Table 3.1; Table B.1'),
 C('c20', "EDM PoseBusters all-tests pass rate with distortion conditioning: GEOM 62.2% to 68.8%, ZINC 40.0% to 74.5%, QM9 81.1% to 46.9%.", 's3.4.2', 'j5', ['79', '85'], 'Table 3.2'),
 C('c21', "On ZINC, conditioning raised atom-connectivity pass rate from 62.4% to 95.7% and bond-length pass rate from 65.0% to 94.1%.", 's3.4.2', 'j5', ['79'], 'Table 3.2'),
 C('c22', "XTB energy labels: GEOM 70% to 84% PoseBusters, QM9 81% to 19%, ZINC 40% to 36% (n = 100).", 's3.4.3', 'j6', ['82'], 'Table 3.3'),
 C('c23', "GCDM on ZINC: PoseBusters 40.8% to 66.5%; on GEOM 77.8% to 79.7%. MolFM on GEOM: 80.8% to 46.8%; on ZINC 42.3% to 45.9%.", 's3.4.4', 'j7', ['82', '83'], 'Table 3.5'),
 C('c24', "The method is strongest for diffusion models on larger drug-like molecules, limited for QM9, inconsistent for flow matching.", 's3.5', 'j7', ['84'], None),
 C('c25', "Centroid-only control with ground-truth blocks: 48/100 pass RDKit sanitisation; the full diffusion model reaches about 4%.", 's4.4.1', 'j8', ['97', '100'], 'Table 4.1'),
 C('c26', "Plane alignment post-processing gives 10.8% RDKit sanitisation, mostly failing on inter-block connectivity.", 's4.4.2', 'j8', ['98'], 'Table 4.1'),
 C('c27', "With orientation vectors the control rises to 89/100 and generation reaches 27.2% (full BRICS, 172 block types) and 51.7% (reduced library, 23 types), against 84.7% for the atomistic model.", 's4.4.3', 'j9', ['93', '99', '100'], 'Table 4.1'),
 C('c28', "Later work reports >94% validity for HierDiff (GEOM) and 97.5% for CMD-GEN; these metrics are not necessarily the same as RDKit sanitisation, so the comparison is indicative only.", 's4.5', 'j9', ['100', '101'], None, conf='medium'),
 C('c29', "OpenFold with constant scaling: modest gains for coordinates and single representation, none for frames; all conditioning worsened 7VPL and 8CXO.", 's5.4.1.1', 'j10', ['111'], 'Fig 5.2'),
 C('c30', "Best OpenFold scheme (frames, 0.1, 3, block and global) improved 9 of 10 targets but all improvements were marginal; adaptive updates cut 8FEI from 3.58 to 2.20 Å and 6LN8 from 5.25 to 4.62 Å.", 's5.4.1.3', 'j10', ['116'], 'Fig 5.6'),
 C('c31', "Boltz-2 gradient conditioning: 8FEI 20.0 to 2.4 Å and 8CXO 11.7 to 7.7 Å; worse for 6LLY and 7VLR.", 's5.4.2.1', 'j11', ['118'], 'Fig 5.7; Table 5.1'),
 C('c32', "MSA subsampling alone improved 7VLR and 7VPL, which gradient conditioning alone made worse; it is inconsistent, with at most five MSAs tried.", 's5.4.2.2~only-msa-subsampling', 'j12', ['119', '120'], 'Fig 5.8'),
 C('c33', "Combining MSA subsampling and gradients was the best approach excluding 8FEI; 2048 sequences gave the lowest RMSD on only 6 of 10 targets.", 's5.4.2.2~combining-with-gradient-based-optimisation', 'j12', ['120', '121'], 'Fig 5.9'),
 C('c34', "All Ch 5 results use simulated ideal density maps, alignment to the ground-truth structure, ten monomer targets and Cα-RMSD only.", 's5.3.3', 'j12', ['107', '108', '111'], 'Table 5.1'),
 C('c35', "With currently available datasets it is impossible to train scoring functions entirely free from bias; large, consistently modelled public protein-ligand datasets are needed.", 's6.1', 'j13', ['124'], None),
 C('c36', "Four lessons: interpretability, negative data, block-encoding difficulty, early intervention plus stochasticity for guiding AlphaFold-like predictors.", 's6.4', 'j13', ['126'], None),
]

# ------------------------------------------------------------------------ inferred / verbal (non cross-reference) edges
def E(i, src, tgt, typ, reason, pages, basis='inferred', conf='medium'):
    return dict(id=i, source=src, target=tgt, type=typ, kind='semantic', basis=basis, confidence=conf, reason=reason, source_pages=pages)
SEMANTIC = [
 E('i1', 's1.4.2', 's2.3', 'motivates', "Ch 1 sets out dataset bias in ML scoring functions; Ch 2 starts from that problem.", ['25', '26', '35'], conf='high'),
 E('i2', 's1.4.3.2', 's2.5.1.1', 'same_concept', "Ch 1 says biased VS tools are often used to evaluate generative models, so debiased scoring matters beyond screening (my reading).", ['29', '49'], conf='low'),
 E('i3', 's1.3.4', 's2.4.1', 'reuses_method', "EGNN layers introduced in 1.3.4 are the core of PointVS.", ['15', '16', '37', '130'], conf='high'),
 E('i4', 's1.4.4', 's2.4.5.4', 'builds_on', "Fragment elaboration with ML (1.4.4) is what STRIFE does in Ch 2.", ['29', '46'], conf='high'),
 E('i5', 's1.3.5', 's3.3.1', 'reuses_method', "Diffusion models (1.3.5) underlie EDM, GCDM and Ch 3.", ['16', '17', '70'], conf='high'),
 E('i6', 's1.4.1.1', 's5.3', 'reuses_method', "OpenFold and Boltz-2 described in 1.4.1.1 are the models modified in Ch 5.", ['20', '21', '106'], conf='high'),
 E('i7', 's1.4.1.2~alphafold-based-methods', 's5.4.2.2', 'builds_on', "ROCKET and CryoBoltz (1.4.1.2) are named as the inspiration for MSA subsampling (stated p. 119).", ['23', '119'], basis='stated', conf='high'),
 E('i8', 's2.6', 's3.1', 'motivates', "Ch 2's closing paragraph says the next chapter explores diffusion-based de novo design and its plausibility.", ['63', '68'], basis='stated', conf='high'),
 E('i9', 's3.5', 's4.1', 'motivates', "Ch 3 ends by introducing a complementary approach, which Ch 4 opens by following on from 'the previous chapter'.", ['84', '87'], basis='stated', conf='high'),
 E('i10', 's3.3.3', 's4.3.3', 'reuses_method', "Ch 4 intended to use the same PoseBusters and RDKit metrics as Ch 3 (stated p. 97).", ['73', '74', '97'], basis='stated', conf='high'),
 E('i11', 's3.3.4.2', 's4.3.2.1', 'same_dataset', "GEOM is the training source in both chapters (Ch 4 refers back to Ch 3 for its description).", ['75', '92'], basis='stated', conf='high'),
 E('i12', 's3.4.2', 's4.4.3', 'same_dataset', "The 84.7% RDKit sanitisation of the atomistic GEOM baseline (Table 3.2) is the comparator for the block models.", ['85', '99', '100'], conf='high'),
 E('i13', 's4.3.2.3', 's1.4.1.1~alphafold2', 'same_concept', "The orientation descriptor is inspired by AlphaFold's per-residue local coordinate frames (stated p. 95; frames described p. 19).", ['19', '95'], basis='stated', conf='high'),
 E('i14', 's4.3.2.2~decomposition-with-standardised-fragments', 's2.5.3', 'same_concept', "The proposed scaffold-then-decorate step could be guided by pharmacophoric hotspot maps, the object produced in 2.5.3.", ['94', '57'], conf='medium'),
 E('i15', 's4.4.1', 's4.4.3', 'motivates', "Centroid-only failure made explicit orientation 'an essential next step' (p. 97).", ['97', '99'], basis='stated', conf='high'),
 E('i16', 's4.4.2', 's4.4.3', 'motivates', "Failure of plane alignment 'motivates' learned orientation (p. 98).", ['98', '99'], basis='stated', conf='high'),
 E('i17', 's4.5', 's4.4.3', 'answers_limitation', "Later hierarchical models with learned decoders solve the orientation problem that limited the block models.", ['99', '100', '101'], basis='stated', conf='high'),
 E('i18', 's5.4.1.1', 's5.4.1.2', 'motivates', "The strength-versus-stability trade-off led to decay schedules (p. 112).", ['112'], basis='stated', conf='high'),
 E('i19', 's5.4.1.3', 's5.4.2', 'motivates', "Limited OpenFold success is the stated reason for trying Boltz-2 (p. 116).", ['116'], basis='stated', conf='high'),
 E('i20', 's5.3.2', 's5.4.1.3', 'answers_limitation', "MSA subsampling is introduced to counter gradient methods becoming trapped in local minima (p. 110; p. 116).", ['110', '116'], basis='stated', conf='high'),
 E('i21', 's5.4.2.1', 's5.4.2.2', 'motivates', "Inconsistent gradient-only results suggested late intervention was insufficient, leading to MSA subsampling (p. 119).", ['119'], basis='stated', conf='high'),
 E('i22', 's2.5.1.2', 's2.5.2', 'motivates', "Debiased performance is only circumstantial, so attribution is applied (p. 52).", ['52'], basis='stated', conf='high'),
 E('i23', 's2.5.2.2', 's2.5.3', 'motivates', "Having shown attribution finds important interactions, it is used to extract hotspots (p. 57).", ['57'], basis='stated', conf='high'),
 E('i24', 's2.5.3.2', 's2.5.4', 'motivates', "Hotspots shown to be consistent, so elaboration tests whether they are also useful (p. 60).", ['60'], basis='stated', conf='high'),
 E('i25', 'sA.4', 's2.5.4', 'builds_on', "Case study applies PointVS hotspots with STRIFE to a real fragment-to-lead campaign; no cross-reference is given in the main text.", ['133', '134'], conf='medium'),
 E('i26', 's2.5.1.1', 's6.1', 'answers_limitation', "Ch 6 turns the leakage finding into a call for large consistent public datasets.", ['49', '124'], conf='medium'),
 E('i27', 's2.5.2', 's6.1', 'same_concept', "Ch 6 argues interpretability should be expected of VS models, generalising the Ch 2 attribution work.", ['52', '124'], conf='high'),
 E('i28', 's3.4.3', 's3.4.2', 'builds_on', "Energy labelling re-uses the distorted datasets from the distortion-factor experiments (p. 80).", ['80'], basis='stated', conf='high'),
 E('i29', 's3.4.4', 's3.4.2', 'builds_on', "GCDM and MolFM are trained on the same distorted datasets with the Ch 3 settings.", ['82'], conf='high'),
 E('i30', 's4.1', 's3.5', 'same_concept', "Both chapters target physical plausibility of diffusion-generated molecules (Ch 4 opens 'as highlighted in the previous chapter').", ['84', '87'], basis='stated', conf='high'),
 E('i31', 's5.3.1', 's5.4.2.1', 'reuses_method', "The same overlap-gradient method is applied in OpenFold and in Boltz-2 (p. 107).", ['107', '117'], basis='stated', conf='high'),
 E('i32', 's3.4.1', 's6.2', 'same_concept', "Negative data as a reusable lesson is stated in Ch 6 (also pp. 125-126).", ['77', '125', '126'], conf='high'),
]

ANOMALIES = [
 dict(id='a1', where="Appendix A.3 (p. 133)", what="Text says the 20 PDBBind Core structures were 'used in section 3.4.2'; Table 2.5 caption (p. 57) and section 2.5.2.2 (p. 57) give Appendix A.3 for those IDs, so 2.5.2.2 is almost certainly meant. The extracted cross-reference is kept but flagged low confidence.", pages=['57', '133']),
 dict(id='a2', where="Appendix A.3 (p. 133)", what="The same paragraph lists 28 PDB IDs while the text says 20 structures.", pages=['133']),
 dict(id='a3', where="Appendix A.4 (pp. 133-134)", what="Text says attribution was run on 18 FGFR1 structures; 16 PDB codes are listed.", pages=['133', '134']),
 dict(id='a4', where="Section 3.4.4 (p. 82) vs Table 3.5", what="Text refers to 'Tables 3.4a and 3.4b'; the only caption is Table 3.5 (a) GCDM, (b) MolFM. No Table 3.4 exists.", pages=['82']),
 dict(id='a5', where="Appendix B.2 (p. 138) vs Table 3.5 (p. 82)", what="Appendix B.2's MolFM GEOM baseline row is identical to its GCDM GEOM baseline row (PoseBusters 77.8%), and the MolFM conditioned row (78.7%) is close to GCDM's (79.7%), while Table 3.5(b) gives MolFM GEOM 80.8% baseline and 46.8% conditioned. The chapter-3 text (p. 83) matches Table 3.5, so the appendix rows look mislabelled or copied. Treat MolFM GEOM numbers from the main text.", pages=['82', '83', '138']),
 dict(id='a6', where="Section 4.4.2 (p. 98)", what="Refers to 'Table 1' for the 10.8% result; the captioned table is Table 4.1 (p. 100).", pages=['98', '100']),
 dict(id='a7', where="Section 2.4.5.4 (p. 47)", what="Table 2.6 is cited in the Methods but appears in the Results (p. 61).", pages=['47', '61']),
 dict(id='a8', where="Appendix B.2 (p. 137-138)", what="The full PoseBusters table has no caption or number, so it is not counted as a numbered table; it is counted manually as one uncaptioned table.", pages=['138']),
 dict(id='a9', where="PDF pages 1-2", what="PDF index 1 is the cover and index 2 is an unnumbered page repeating the abstract; neither has a printed page number and neither is mapped to a printed page.", pages=[]),
]

# ------------------------------------------------------------------------ entities
# (id, name, category, regex, description)
ENT = [
 ('pointvs', "PointVS", 'method', r'PointVS', "E(n)-equivariant GNN scoring function with edge-attention attribution (Ch 2)."),
 ('egnn', "EGNN / equivariant GNN", 'method', r'EGNN|E\(n\)[- ]equivariant|E\(3\)[- ]equivariant', "Message passing that updates features and coordinates equivariantly (1.3.4)."),
 ('gnn', "Graph neural network", 'method', r'\bGNNs?\b|(?i:graph neural network)', "Neural network on graphs (atoms and bonds)."),
 ('cnn', "Convolutional neural network", 'method', r'\bCNNs?\b|(?i:convolutional neural network)', "Grid-based network; used by gnina; loses atom identity deeper in the net."),
 ('attribution', "Input attribution", 'term', r'(?i:attribution)', "Scoring which inputs a model's prediction depends on."),
 ('edge_attention', "Edge attention", 'method', r'(?i:edge[- ]attention)', "Learned 0-1 edge weights in PointVS used as the attribution signal."),
 ('masking', "Atom / bond masking", 'method', r'(?i:(?:atom|bond) masking)', "Importance as score change when an atom or edge is removed."),
 ('gnina', "gnina", 'software', r'\bgnina\b', "CNN scoring and docking tool; baseline and attribution comparison."),
 ('ign', "InteractionGraphNet (IGN)", 'software', r'InteractionGraphNet|\bIGN\b', "Graph-based scoring function used for bond-masking comparison."),
 ('plip', "PLIP", 'software', r'\bPLIP\b', "Distance-rule protein-ligand interaction profiler used as reference."),
 ('strife', "STRIFE", 'software', r'\bSTRIFE\b', "Graph generative model for fragment elaboration given hotspots."),
 ('hotspots_api', "Hotspots API", 'software', r'Hotspots API|API hotspots', "Data-driven (CSD) hotspot detector used as baseline."),
 ('hotspot', "Hotspot", 'term', r'(?i:hotspots?)\b', "Pocket region contributing disproportionately to binding."),
 ('vina', "AutoDock Vina", 'software', r'Autodock Vina|AutoDock Vina', "Classical docking and scoring baseline."),
 ('gold', "GOLD docking", 'software', r'\bGOLD\b', "Docking software used to score elaborations."),
 ('vs', "Virtual screening", 'term', r'(?i:virtual screening)|\bVS\b', "Computational prioritisation of candidate binders."),
 ('fbdd', "Fragment-based design / elaboration", 'term', r'(?i:fragment[- ]based|fragment elaboration)|\bFBDD\b', "Growing, linking or merging fragment hits."),
 ('bias', "Dataset bias / leakage", 'term', r'(?i:dataset bias|biases|leakage|debias|biased)', "Models exploiting benchmark artefacts rather than physics."),
 ('interpretability', "Interpretability", 'term', r'(?i:interpretab)', "Checking what a model's prediction rests on."),
 ('equivariance', "Equivariance / invariance", 'term', r'(?i:equivarian|invarian)', "Symmetry property of models on 3D data."),
 ('diffusion', "Diffusion models", 'method', r'(?i:diffusion)', "Generative models that learn to reverse a noising process."),
 ('edm', "EDM", 'method', r'\bEDM\b', "First E(3)-equivariant diffusion model for 3D molecules."),
 ('gcdm', "GCDM", 'method', r'\bGCDM\b', "Geometry-complete diffusion model."),
 ('molfm', "MolFM", 'method', r'MolFM', "Flow-matching molecule generator."),
 ('distortion', "Distortion / quality conditioning", 'method', r'(?i:distort|conformer quality)', "Negative examples with a distortion label (Ch 3)."),
 ('negative_data', "Negative data", 'term', r'(?i:negative (?:data|examples|training))', "Low-quality examples used to define the boundary of valid space."),
 ('xtb', "XTB", 'software', r'\bXTB\b|GFN2', "Semi-empirical tight-binding energies."),
 ('brics', "BRICS", 'method', r'\bBRICS\b', "Rule-based fragmentation into retrosynthetic building blocks."),
 ('hierdiff', "HierDiff / CMD-GEN / SubGDiff", 'method', r'HierDiff|CMD-GEN|SubGDiff', "Later hierarchical or substructure-aware generators."),
 ('posebusters', "PoseBusters", 'software', r'PoseBusters', "Physical-validity checks for molecules and poses."),
 ('rdkit', "RDKit", 'software', r'RDKit', "Cheminformatics toolkit; sanitisation pass rate."),
 ('openbabel', "Open Babel", 'software', r'Open ?Babel', "Assigns bonds from coordinates."),
 ('plausibility', "Physical plausibility / validity", 'term', r'(?i:plausib|physically (?:valid|realistic)|validity)', "Whether generated molecules obey chemistry and physics."),
 ('synthesisability', "Synthesisability", 'term', r'(?i:synthesisab|synthetic accessib)', "Motivation for building-block generation."),
 ('alphafold', "AlphaFold 2 / 3", 'method', r'AlphaFold ?[23]?', "Structure-prediction models (frames; pairformer and diffusion)."),
 ('openfold', "OpenFold", 'software', r'OpenFold', "Open AF2 reimplementation; Ch 5 target."),
 ('boltz', "Boltz-1 / Boltz-2", 'software', r'Boltz-?[12]?', "Open AF3-style models; Ch 5 target."),
 ('rocket_cryoboltz', "ROCKET / CryoBoltz", 'method', r'ROCKET|Cryo-?Boltz', "Existing cryo-EM-conditioned AlphaFold methods."),
 ('modelangelo', "ModelAngelo", 'method', r'ModelAngelo', "GNN-based direct map-interpretation model builder."),
 ('msa', "MSA / MSA subsampling", 'term', r'\bMSAs?\b|(?i:multiple sequence alignment|subsampl)', "Evolutionary input; subsampling injects stochasticity."),
 ('cryoem', "Cryo-EM model building", 'term', r'(?i:cryo-?EM)', "Fitting an atomic model into a density map."),
 ('gradopt', "Gradient-based map conditioning", 'method', r'(?i:gradient-based)', "Overlap gradient added to a model's internal state."),
 ('local_minima', "Local minima", 'term', r'(?i:local minim)', "Why late-stage gradient guidance stalls."),
 ('simulated_maps', "Simulated density maps", 'term', r'simulated (?:cryo-EM |density )?(?:maps?|data)|simulated density', "Ideal maps built from the ground truth (a stated limitation)."),
 ('casf16', "CASF16", 'dataset', r'CASF', "Standard scoring-function benchmark found to leak."),
 ('pdbbind', "PDBBind", 'dataset', r'PDBBind', "Protein-ligand complexes with affinities."),
 ('redocked', "Redocked2020", 'dataset', r'Redocked', "Pose-classification training set."),
 ('dude', "DUD / DUD-E", 'dataset', r'DUD-E|\bDUD\b', "Decoy sets with known biases."),
 ('qm9', "QM9", 'dataset', r'QM9', "Small molecules (<=9 heavy atoms)."),
 ('geom', "GEOM", 'dataset', r'\bGEOM', "Drug-like conformer dataset used in Chs 3-4."),
 ('zinc', "ZINC", 'dataset', r'\bZINC\b', "Commercially available compounds; 660k subset in Ch 3."),
 ('fragalysis', "Fragalysis / SARS-CoV-2 targets", 'dataset', r'fragalysis|\bMpro\b|Mac1|NSP14', "Fragment screens used for hotspot tests."),
 ('tankyrase', "Tankyrase-2 complexes", 'dataset', r'Tankyrase', "Three complexes for the attribution-versus-PLIP test."),
 ('fgfr1', "FGFR1 / erdafitinib", 'dataset', r'FGFR1|erdafitinib', "Case study of a fragment-derived drug."),
 ('cryo_targets', "Ch 5 test targets", 'dataset', r'5YW7|6LLY|6LN8|7N70|7O3D|7RAV|7VLR|7VPL|8CXO|8FEI', "Ten monomer targets with 3-20 Å vanilla error."),
]
